#priority 1
//File created by Nykrdaudr
//removing facades from JEI
//SRP with addons

mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:buglinhive"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:buglinhive"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:buglinhivefilled"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:buglinhivefilled"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:concentratedfleshslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:concentratedfleshslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:crackedparasitebrick"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:crackedparasitebrick"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratealteredtendons"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratealteredtendons"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:crateassimilatedflesh"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:crateassimilatedflesh"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratediseasedheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratediseasedheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratedriedtendons"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratedriedtendons"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:crateessentialsegment"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:crateessentialsegment"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratehardenedbonehandle"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratehardenedbonehandle"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:crateinfectiousbladefragment"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:crateinfectiousbladefragment"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratelivingcore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratelivingcore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratelongarmsarmorfragment"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratelongarmsarmorfragment"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratemanducaterorb"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratemanducaterorb"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratenoxiousbrain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratenoxiousbrain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:crateparasiticlump"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:crateparasiticlump"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratereekerfang"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratereekerfang"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:craterupterviscera"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:craterupterviscera"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratestrangebone"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratestrangebone"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratesummonercore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratesummonercore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratetoxiclung"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratetoxiclung"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:cratevileshell"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:cratevileshell"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:crateyelloweyebone"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:crateyelloweyebone"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:dirtstone"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:dirtstone"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:dirtstonechiseled"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:dirtstonechiseled"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:dirtstonecut"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:dirtstonecut"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:dirtstoneslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:dirtstoneslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:fleshslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:fleshslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:hardenedfleshblock"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:hardenedfleshblock"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:hardenedfleshslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:hardenedfleshslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:infestedbrickmossy"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:infestedbrickmossy"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:infestedstonebrick"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:infestedstonebrick"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:infestedstonebrickchiseled"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:infestedstonebrickchiseled"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:infestedstonebrickcracked"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:infestedstonebrickcracked"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:infestedstonebrickslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:infestedstonebrickslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:infestedstoneslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:infestedstoneslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:infstone"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:infstone"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:infstonechiseled"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:infstonechiseled"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:infstonecut"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:infstonecut"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:infstoneslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:infstoneslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:mossyparasitebrick"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:mossyparasitebrick"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:mudstone"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:mudstone"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:mudstonechiseled"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:mudstonechiseled"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:mudstoneslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:mudstoneslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:mudstonesmooth"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:mudstonesmooth"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:parasiticstoneslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:parasiticstoneslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:plankscyan"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:plankscyan"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:plankscyanslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:plankscyanslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:planksgreen"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:planksgreen"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:planksgreenslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:planksgreenslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:plankspurple"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:plankspurple"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:plankspurpleslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:plankspurpleslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:redstonebrick"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:redstonebrick"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:redstonebrickchiseled"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:redstonebrickchiseled"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:redstonebrickslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:redstonebrickslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "nocubessrpsurvival:reinforcedplating"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "nocubessrpsurvival:reinforcedplating"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:veinslab_double"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "default"}, Name: "nocubessrpsurvival:veinslab_double"}}]}}));
//============================================================================================================================================================================================
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "overlast:blockpurifier"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "overlast:blockpurifier"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "false"}, Name: "overlast:blue_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "false"}, Name: "overlast:blue_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "true"}, Name: "overlast:blue_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "true"}, Name: "overlast:blue_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "false"}, Name: "overlast:blue_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "false"}, Name: "overlast:blue_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "true"}, Name: "overlast:blue_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "true"}, Name: "overlast:blue_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "false"}, Name: "overlast:brown_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "false"}, Name: "overlast:brown_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "true"}, Name: "overlast:brown_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "true"}, Name: "overlast:brown_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "false"}, Name: "overlast:brown_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "false"}, Name: "overlast:brown_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "true"}, Name: "overlast:brown_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "true"}, Name: "overlast:brown_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "overlast:crops"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "overlast:crops"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "overlast:final_specimen"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "overlast:final_specimen"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "false"}, Name: "overlast:orange_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "false"}, Name: "overlast:orange_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "true"}, Name: "overlast:orange_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "true"}, Name: "overlast:orange_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "false"}, Name: "overlast:orange_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "false"}, Name: "overlast:orange_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "true"}, Name: "overlast:orange_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "true"}, Name: "overlast:orange_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "false"}, Name: "overlast:red_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "false"}, Name: "overlast:red_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "true"}, Name: "overlast:red_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "true"}, Name: "overlast:red_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "false"}, Name: "overlast:red_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "false"}, Name: "overlast:red_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "true"}, Name: "overlast:red_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "true"}, Name: "overlast:red_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "overlast:specimen_cell"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "overlast:specimen_cell"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "overlast:specimen_farm"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "overlast:specimen_farm"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "overlast:specimen_infect"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "overlast:specimen_infect"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "overlast:summer_core"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "overlast:summer_core"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "overlast:winter_core"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "overlast:winter_core"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "false"}, Name: "overlast:yellow_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "false"}, Name: "overlast:yellow_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "true"}, Name: "overlast:yellow_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "false", decayable: "true"}, Name: "overlast:yellow_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "false"}, Name: "overlast:yellow_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "false"}, Name: "overlast:yellow_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "true"}, Name: "overlast:yellow_leaves"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {check_decay: "true", decayable: "true"}, Name: "overlast:yellow_leaves"}}]}}));
//============================================================================================================================================================================================
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "0"}, Name: "srparasites:biomeheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "0"}, Name: "srparasites:biomeheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "1"}, Name: "srparasites:biomeheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "1"}, Name: "srparasites:biomeheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "2"}, Name: "srparasites:biomeheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "2"}, Name: "srparasites:biomeheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "3"}, Name: "srparasites:biomeheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "3"}, Name: "srparasites:biomeheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "srparasites:biomepurifier"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "srparasites:biomepurifier"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Name: "srparasites:bloodyice"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Name: "srparasites:bloodyice"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "0"}, Name: "srparasites:colonyheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "0"}, Name: "srparasites:colonyheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "1"}, Name: "srparasites:colonyheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "1"}, Name: "srparasites:colonyheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "2"}, Name: "srparasites:colonyheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "2"}, Name: "srparasites:colonyheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "3"}, Name: "srparasites:colonyheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "3"}, Name: "srparasites:colonyheart"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "0"}, Name: "srparasites:colonyoutpost"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "0"}, Name: "srparasites:colonyoutpost"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "1"}, Name: "srparasites:colonyoutpost"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "1"}, Name: "srparasites:colonyoutpost"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "2"}, Name: "srparasites:colonyoutpost"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "2"}, Name: "srparasites:colonyoutpost"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "3"}, Name: "srparasites:colonyoutpost"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "3"}, Name: "srparasites:colonyoutpost"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "one"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "one"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "two"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "two"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "three"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "three"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "four"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "four"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "five"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "five"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "six"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "six"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "seven"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "seven"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "eight"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "eight"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "nine"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "nine"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "ten"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "ten"}, Name: "srparasites:evolutionlure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "co"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "co"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "dia"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "dia"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "eme"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "eme"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "gol"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "gol"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "iro"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "iro"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "lap"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "lap"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "red"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "red"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "un"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "un"}, Name: "srparasites:infestedore"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {stage: "0"}, Name: "srparasites:infestedrubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {stage: "0"}, Name: "srparasites:infestedrubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {stage: "1"}, Name: "srparasites:infestedrubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {stage: "1"}, Name: "srparasites:infestedrubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {stage: "2"}, Name: "srparasites:infestedrubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {stage: "2"}, Name: "srparasites:infestedrubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {stage: "3"}, Name: "srparasites:infestedrubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {stage: "3"}, Name: "srparasites:infestedrubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {stage: "4"}, Name: "srparasites:infestedrubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {stage: "4"}, Name: "srparasites:infestedrubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {stage: "5"}, Name: "srparasites:infestedrubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {stage: "5"}, Name: "srparasites:infestedrubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {stage: "0"}, Name: "srparasites:infestedstain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {stage: "0"}, Name: "srparasites:infestedstain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {stage: "1"}, Name: "srparasites:infestedstain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {stage: "1"}, Name: "srparasites:infestedstain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {stage: "2"}, Name: "srparasites:infestedstain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {stage: "2"}, Name: "srparasites:infestedstain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {stage: "3"}, Name: "srparasites:infestedstain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {stage: "3"}, Name: "srparasites:infestedstain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {stage: "4"}, Name: "srparasites:infestedstain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {stage: "4"}, Name: "srparasites:infestedstain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {stage: "5"}, Name: "srparasites:infestedstain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {stage: "5"}, Name: "srparasites:infestedstain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {axis: "x"}, Name: "srparasites:infestedtrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {axis: "x"}, Name: "srparasites:infestedtrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {axis: "y"}, Name: "srparasites:infestedtrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {axis: "y"}, Name: "srparasites:infestedtrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {axis: "z"}, Name: "srparasites:infestedtrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {axis: "z"}, Name: "srparasites:infestedtrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "flesh"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "flesh"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "bone"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "bone"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "stone"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "stone"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "stonedebris"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "stonedebris"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "wood"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "wood"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "bricks"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "bricks"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "metal"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "metal"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "obsidian"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "obsidian"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "fungus"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "fungus"}, Name: "srparasites:parasiterubble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {half: "top", variant: "default"}, Name: "srparasites:parasiterubble_slabdouble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {half: "top", variant: "default"}, Name: "srparasites:parasiterubble_slabdouble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {half: "bottom", variant: "default"}, Name: "srparasites:parasiterubble_slabdouble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {half: "bottom", variant: "default"}, Name: "srparasites:parasiterubble_slabdouble"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "wall"}, Name: "srparasites:parasiterubbledense"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "wall"}, Name: "srparasites:parasiterubbledense"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "biome"}, Name: "srparasites:parasiterubbledense"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "biome"}, Name: "srparasites:parasiterubbledense"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "colony"}, Name: "srparasites:parasiterubbledense"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "colony"}, Name: "srparasites:parasiterubbledense"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "dirt"}, Name: "srparasites:parasitestain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "dirt"}, Name: "srparasites:parasitestain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "mud"}, Name: "srparasites:parasitestain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "mud"}, Name: "srparasites:parasitestain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "flesh"}, Name: "srparasites:parasitestain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "flesh"}, Name: "srparasites:parasitestain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "feeler"}, Name: "srparasites:parasitestain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "feeler"}, Name: "srparasites:parasitestain"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "0"}, Name: "srparasites:parasitestructure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "0"}, Name: "srparasites:parasitestructure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "1"}, Name: "srparasites:parasitestructure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "1"}, Name: "srparasites:parasitestructure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "2"}, Name: "srparasites:parasitestructure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "2"}, Name: "srparasites:parasitestructure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {active: "3"}, Name: "srparasites:parasitestructure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {active: "3"}, Name: "srparasites:parasitestructure"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "ball", axis: "x"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "ball", axis: "x"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "tree", axis: "x"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "tree", axis: "x"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "plant", axis: "x"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "plant", axis: "x"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "ball", axis: "y"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "ball", axis: "y"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "tree", axis: "y"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "tree", axis: "y"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "plant", axis: "y"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "plant", axis: "y"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "ball", axis: "z"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "ball", axis: "z"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "tree", axis: "z"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "tree", axis: "z"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 0 as byte, states: [{state: {Properties: {variant: "plant", axis: "z"}, Name: "srparasites:parasitetrunk"}}]}}));
mods.jei.JEI.removeAndHide(<buildcraftsilicon:plug_facade>.withTag({facade: {isHollow: 1 as byte, states: [{state: {Properties: {variant: "plant", axis: "z"}, Name: "srparasites:parasitetrunk"}}]}}));
