#priority 5
//File created by Nykrdaudr
//Crafting table recipes
//MISC


//============================================================================================================================================================================================
//PVJ
recipes.addShaped("mud_1", <pvj:mud> * 8, [[<minecraft:dirt:1>, <minecraft:dirt:1>, <minecraft:dirt:1>], [<minecraft:dirt:1>, <minecraft:water_bucket>, <minecraft:dirt:1>], [<minecraft:dirt:1>, <minecraft:dirt:1>, <minecraft:dirt:1>]]);
recipes.addShaped("mud_2", <pvj:mud> * 8, [[<ore:dirt>, <ore:dirt>, <ore:dirt>], [<ore:dirt>, <minecraft:water_bucket>, <ore:dirt>], [<ore:dirt>, <ore:dirt>, <ore:dirt>]]);
recipes.addShaped("wet_adobe", <pvj:wet_adobe> * 9, [[<minecraft:clay>, <ore:sand>, <minecraft:clay>], [<ore:sand>, <ore:dirt>, <ore:sand>], [<minecraft:clay>, <ore:sand>, <minecraft:clay>]]);
recipes.addShapeless("slime_droplets", <pvj:slime_droplet> * 9, [<minecraft:slime_ball>]);
recipes.addShaped("redwood_bark", <pvj:redwood_bark:0>, [[<pvj:log_redwood:0>, <pvj:log_redwood:0>, <pvj:log_redwood:0>], [<pvj:log_redwood:0>, <pvj:log_redwood:0>, <pvj:log_redwood:0>], [<pvj:log_redwood:0>, <pvj:log_redwood:0>, <pvj:log_redwood:0>]]);
recipes.addShapeless("redwood_log_from_bark", <pvj:log_redwood:0> * 9, [<pvj:redwood_bark:0>]);
recipes.addShaped("leaf_carpet_0", <pvj:fallenleaves_oak> * 3, [[<minecraft:leaves:0>, <minecraft:leaves:0>, <minecraft:leaves:0>]]);
recipes.addShaped("leaf_carpet_1", <pvj:fallenleaves_oak> * 3, [[<quark:variant_leaves:0>, <quark:variant_leaves:0>, <quark:variant_leaves:0>]]);
recipes.addShaped("leaf_carpet_2", <pvj:fallenleaves_birch> * 3, [[<minecraft:leaves:1>, <minecraft:leaves:1>, <minecraft:leaves:1>]]);
recipes.addShaped("leaf_carpet_3", <pvj:fallenleaves_spruce> * 3, [[<minecraft:leaves:2>, <minecraft:leaves:2>, <minecraft:leaves:2>]]);
recipes.addShaped("leaf_carpet_4", <pvj:fallenleaves_jungle> * 3, [[<minecraft:leaves:3>, <minecraft:leaves:3>, <minecraft:leaves:3>]]);
recipes.addShaped("leaf_carpet_5", <pvj:fallenleaves_darkoak> * 3, [[<minecraft:leaves2:0>, <minecraft:leaves2:0>, <minecraft:leaves2:0>]]);
recipes.addShaped("leaf_carpet_6", <pvj:fallenleaves_acacia> * 3, [[<minecraft:leaves2:1>, <minecraft:leaves2:1>, <minecraft:leaves2:1>]]);
recipes.addShaped("leaf_carpet_8", <pvj:fallenleaves_willow> * 3, [[<pvj:leaves_willow:*>, <pvj:leaves_willow:*>, <pvj:leaves_willow:*>]]);
recipes.addShaped("leaf_carpet_9", <pvj:fallenleaves_mangrove> * 3, [[<pvj:leaves_mangrove:*>, <pvj:leaves_mangrove:*>, <pvj:leaves_mangrove:*>]]);
recipes.addShaped("leaf_carpet_10", <pvj:fallenleaves_palm> * 3, [[<pvj:leaves_palm:*>, <pvj:leaves_palm:*>, <pvj:leaves_palm:*>]]);
recipes.addShaped("leaf_carpet_13", <pvj:fallenleaves_redwood> * 3, [[<pvj:leaves_redwood:*>, <pvj:leaves_redwood:*>, <pvj:leaves_redwood:*>]]);
recipes.addShaped("leaf_carpet_14", <pvj:fallenleaves_fir> * 3, [[<pvj:leaves_fir:*>, <pvj:leaves_fir:*>, <pvj:leaves_fir:*>]]);
recipes.addShaped("leaf_carpet_15", <pvj:fallenleaves_pine> * 3, [[<pvj:leaves_pine:*>, <pvj:leaves_pine:*>, <pvj:leaves_pine:*>]]);
recipes.addShaped("leaf_carpet_16", <pvj:fallenleaves_aspen> * 3, [[<pvj:leaves_aspen:*>, <pvj:leaves_aspen:*>, <pvj:leaves_aspen:*>]]);
recipes.addShaped("leaf_carpet_17", <pvj:fallenleaves_red_maple> * 3, [[<pvj:leaves_red_maple:*>, <pvj:leaves_red_maple:*>, <pvj:leaves_red_maple:*>]]);
recipes.addShaped("leaf_carpet_18", <pvj:fallenleaves_orange_maple> * 3, [[<pvj:leaves_orange_maple:*>, <pvj:leaves_orange_maple:*>, <pvj:leaves_orange_maple:*>]]);
recipes.addShaped("leaf_carpet_19", <pvj:fallenleaves_baobab> * 3, [[<pvj:leaves_baobab:*>, <pvj:leaves_baobab:*>, <pvj:leaves_baobab:*>]]);
recipes.addShaped("leaf_carpet_20", <pvj:fallenleaves_cottonwood> * 3, [[<pvj:leaves_cottonwood:*>, <pvj:leaves_cottonwood:*>, <pvj:leaves_cottonwood:*>]]);
recipes.addShaped("leaf_carpet_21", <pvj:fallenleaves_juniper> * 3, [[<pvj:leaves_juniper:*>, <pvj:leaves_juniper:*>, <pvj:leaves_juniper:*>]]);
recipes.addShaped("leaf_carpet_22", <pvj:fallenleaves_juniper_berried> * 3, [[<pvj:leaves_juniper_berried:*>, <pvj:leaves_juniper_berried:*>, <pvj:leaves_juniper_berried:*>]]);
recipes.addShaped("leaf_carpet_23", <pvj:fallenleaves_white_cherry_blossom> * 3, [[<pvj:leaves_white_cherry_blossom:*>, <pvj:leaves_white_cherry_blossom:*>, <pvj:leaves_white_cherry_blossom:*>]]);
recipes.addShaped("leaf_carpet_24", <pvj:fallenleaves_pink_cherry_blossom> * 3, [[<pvj:leaves_pink_cherry_blossom:*>, <pvj:leaves_pink_cherry_blossom:*>, <pvj:leaves_pink_cherry_blossom:*>]]);
recipes.addShaped("leaf_carpet_25", <pvj:fallenleaves_pink_cherry_blossom> * 3, [[<quark:variant_leaves:1>, <quark:variant_leaves:1>, <quark:variant_leaves:1>]]);
recipes.addShaped("leaf_carpet_26", <pvj:fallenleaves_jacaranda> * 3, [[<pvj:leaves_jacaranda:*>, <pvj:leaves_jacaranda:*>, <pvj:leaves_jacaranda:*>]]);
recipes.addShaped("bone_pile", <pvj:bones> * 6, [[null, <minecraft:bone>, null], [<minecraft:bone>, <minecraft:bone>, <minecraft:bone>]]);
recipes.addShaped("leaf_carpet_11", <pvj:fallenleaves_palm> * 3, [[<oe:palm_leaves>, <oe:palm_leaves>, <oe:palm_leaves>]]);
recipes.addShaped("leaf_carpet_12", <pvj:fallenleaves_palm> * 3, [[<oe:palm_leaves_flowering>, <oe:palm_leaves_flowering>, <oe:palm_leaves_flowering>]]);
recipes.addShaped("leaf_carpet_7", <pvj:fallenleaves_dead> * 3, [[<overlast:brown_leaves>, <overlast:brown_leaves>, <overlast:brown_leaves>]]);
recipes.addShaped(<parasitusfix:door_maple> * 3, [[<pvj:planks_maple>, <pvj:planks_maple>, null],[<pvj:planks_maple>, <pvj:planks_maple>, null], [<pvj:planks_maple>, <pvj:planks_maple>, null]]);
recipes.addShaped(<parasitusfix:door_juniper> * 3, [[<pvj:planks_juniper>, <pvj:planks_juniper>, null],[<pvj:planks_juniper>, <pvj:planks_juniper>, null], [<pvj:planks_juniper>, <pvj:planks_juniper>, null]]);
recipes.addShaped(<parasitusfix:door_cherry_blossom> * 3, [[<pvj:planks_cherry_blossom>, <pvj:planks_cherry_blossom>, null],[<pvj:planks_cherry_blossom>, <pvj:planks_cherry_blossom>, null], [<pvj:planks_cherry_blossom>, <pvj:planks_cherry_blossom>, null]]);
recipes.addShaped(<parasitusfix:door_aspen> * 3, [[<pvj:planks_aspen>, <pvj:planks_aspen>, null],[<pvj:planks_aspen>, <pvj:planks_aspen>, null], [<pvj:planks_aspen>, <pvj:planks_aspen>, null]]);
recipes.addShaped(<parasitusfix:door_cottonwood> * 3, [[<pvj:planks_cottonwood>, <pvj:planks_cottonwood>, null],[<pvj:planks_cottonwood>, <pvj:planks_cottonwood>, null], [<pvj:planks_cottonwood>, <pvj:planks_cottonwood>, null]]);
recipes.addShaped(<parasitusfix:door_baobab> * 3, [[<pvj:planks_baobab>, <pvj:planks_baobab>, null],[<pvj:planks_baobab>, <pvj:planks_baobab>, null], [<pvj:planks_baobab>, <pvj:planks_baobab>, null]]);
recipes.addShaped(<parasitusfix:door_redwood> * 3, [[<pvj:planks_redwood>, <pvj:planks_redwood>, null],[<pvj:planks_redwood>, <pvj:planks_redwood>, null], [<pvj:planks_redwood>, <pvj:planks_redwood>, null]]);
recipes.addShaped(<parasitusfix:door_mangrove> * 3, [[<pvj:planks_mangrove>, <pvj:planks_mangrove>, null],[<pvj:planks_mangrove>, <pvj:planks_mangrove>, null], [<pvj:planks_mangrove>, <pvj:planks_mangrove>, null]]);
recipes.addShaped(<parasitusfix:door_willow> * 3, [[<pvj:planks_willow>, <pvj:planks_willow>, null],[<pvj:planks_willow>, <pvj:planks_willow>, null], [<pvj:planks_willow>, <pvj:planks_willow>, null]]);
recipes.addShaped(<parasitusfix:door_palm> * 3, [[<pvj:planks_palm>, <pvj:planks_palm>, null],[<pvj:planks_palm>, <pvj:planks_palm>, null], [<pvj:planks_palm>, <pvj:planks_palm>, null]]);
recipes.addShaped(<parasitusfix:door_pine> * 3, [[<pvj:planks_pine>, <pvj:planks_pine>, null],[<pvj:planks_pine>, <pvj:planks_pine>, null], [<pvj:planks_pine>, <pvj:planks_pine>, null]]);
recipes.addShaped(<parasitusfix:door_fir> * 3, [[<pvj:planks_fir>, <pvj:planks_fir>, null],[<pvj:planks_fir>, <pvj:planks_fir>, null], [<pvj:planks_fir>, <pvj:planks_fir>, null]]);
recipes.addShaped(<parasitusfix:door_jacaranda> * 3, [[<pvj:planks_jacaranda>, <pvj:planks_jacaranda>, null],[<pvj:planks_jacaranda>, <pvj:planks_jacaranda>, null], [<pvj:planks_jacaranda>, <pvj:planks_jacaranda>, null]]);
recipes.addShapeless("redwood_bark_from_log", <pvj:redwood_bark> * 9, [<pvj:redwood>, <pvj:redwood>, <pvj:redwood>, <pvj:redwood>, <pvj:redwood>, <pvj:redwood>, <pvj:redwood>, <pvj:redwood>, <pvj:redwood>]);
recipes.addShapeless("redwood_log_from_bark", <pvj:redwood> * 9, [<pvj:redwood_bark>, <pvj:redwood_bark>, <pvj:redwood_bark>, <pvj:redwood_bark>, <pvj:redwood_bark>, <pvj:redwood_bark>, <pvj:redwood_bark>, <pvj:redwood_bark>, <pvj:redwood_bark>]);
//============================================================================================================================================================================================
//CORALREEF
recipes.addShapeless("coral_blocks", <coralreef:reef:0> * 5, [<oe:purple_coral_block>, <oe:blue_coral_block>, <oe:yellow_coral_block>, <oe:red_coral_block>, <oe:pink_coral_block>]);
furnace.addRecipe(<coralreef:reef:1>, <coralreef:reef:0>, 0.1);
//============================================================================================================================================================================================
//KOOPAS CRITTERS
recipes.addShaped("sticksNdirt", <koopascritters:sticksndirt> * 3, [[<ore:dirt>, <ore:treeLeaves>, <ore:treeLeaves>], [<minecraft:stick>, <ore:dirt>, <minecraft:stick>]]);
//============================================================================================================================================================================================
//OPEN MODULAR TURRETS
recipes.addShaped("chamber_tier_1", <openmodularturrets:intermediate_tiered:5>, [[<ore:stonesCobble>, <ore:stonesCobble>, <ore:stonesCobble>], [null, <ore:plankWood>, <ore:dustRedstone>], [<ore:stonesCobble>, <ore:stonesCobble>, <ore:stonesCobble>]]);
recipes.addShaped("sensor_tier_4", <openmodularturrets:intermediate_tiered:3>, [[<ore:ingotGold>, <netherex:rime_crystal>, <ore:ingotGold>], [<openmodularturrets:intermediate_regular:0>, <openmodularturrets:intermediate_tiered:2>, <openmodularturrets:intermediate_regular:0>], [<ore:gemQuartz>, <netherex:rime_crystal>, <ore:gemQuartz>]]);
recipes.addShaped("sensor_tier_5", <openmodularturrets:intermediate_tiered:4>, [[<quark:duskbound_block>, <ore:dustGlowstone>, <quark:duskbound_block>], [<openmodularturrets:intermediate_regular:0>, <openmodularturrets:intermediate_tiered:3>, <openmodularturrets:intermediate_regular:0>], [<quark:duskbound_block>, <ore:dustGlowstone>, <quark:duskbound_block>]]);
recipes.addShaped("chamber_tier_4", <openmodularturrets:intermediate_tiered:8>, [[<ore:gemQuartz>, <netherex:rime_crystal>, <ore:gemQuartz>], [null, <openmodularturrets:intermediate_tiered:7>, <openmodularturrets:intermediate_regular:0>], [<ore:gemQuartz>, <netherex:rime_crystal>, <ore:gemQuartz>]]);
recipes.addShaped("chamber_tier_5", <openmodularturrets:intermediate_tiered:9>, [[<quark:duskbound_block>, <ore:gemQuartz>, <quark:duskbound_block>], [null, <openmodularturrets:intermediate_tiered:8>, <openmodularturrets:intermediate_regular:0>], [<quark:duskbound_block>, <ore:gemQuartz>, <quark:duskbound_block>]]);
recipes.addShaped("barrel_tier_1", <openmodularturrets:intermediate_tiered:10>, [[<ore:stonesCobble>, <ore:stonesCobble>, <ore:stonesCobble>], [<sevendaystomine:woodplank>, <sevendaystomine:woodplank>, <sevendaystomine:woodplank>], [<ore:stonesCobble>, <ore:stonesCobble>, <ore:stonesCobble>]]);
recipes.addShaped("barrel_tier_4", <openmodularturrets:intermediate_tiered:13>, [[<ore:gemQuartz>, <netherex:rime_crystal>, <ore:gemQuartz>], [null, <openmodularturrets:intermediate_tiered:12>, null], [<ore:gemQuartz>, <netherex:rime_crystal>, <ore:gemQuartz>]]);
recipes.addShaped("barrel_tier_5", <openmodularturrets:intermediate_tiered:14>, [[<quark:duskbound_block>, <quark:duskbound_block>, <quark:duskbound_block>], [<ore:dustGlowstone>, <openmodularturrets:intermediate_tiered:13>, <ore:dustGlowstone>], [<quark:duskbound_block>, <quark:duskbound_block>, <quark:duskbound_block>]]);
recipes.addShaped("cammo_addon", <openmodularturrets:addon_meta:0>, [[null, <techguns:camonet_top:*>, null], [<techguns:camonet:*>, <openmodularturrets:intermediate_tiered:1>, <techguns:camonet:*>], [<buildcraftcore:gear_iron>, <openmodularturrets:intermediate_regular:0>, <buildcraftcore:gear_iron>]]);
recipes.addShaped("damage_boost", <openmodularturrets:addon_meta:1>, [[<ore:ingotIron>, <techguns:itemshared:75>, <ore:ingotIron>], [<techguns:itemshared:75>, <spartanweaponry:material:2>, <techguns:itemshared:75>], [<ore:ingotIron>, <techguns:itemshared:75>, <ore:ingotIron>]]);
recipes.addShaped("recycler", <openmodularturrets:addon_meta:3>, [[<ore:ingotSteel>, <openmodularturrets:intermediate_regular:0>, <ore:ingotSteel>], [<openmodularturrets:intermediate_regular:0>, <techguns:itemshared:94>, <openmodularturrets:intermediate_regular:0>], [<ore:ingotSteel>, <ore:chestWood>, <ore:ingotSteel>]]);
recipes.addShaped("redstone_reactor", <openmodularturrets:addon_meta:4>, [[<ore:nuggetGold>, <ore:blockRedstone>, <ore:nuggetGold>], [<ore:plateLead>, <buildcraftcore:engine:0>, <ore:plateLead>], [<ore:plateLead>, <openmodularturrets:intermediate_regular:0>, <ore:plateLead>]]);
recipes.addShaped("solar_power", <openmodularturrets:addon_meta:6>, [[<ore:paneGlassColorless>, <ore:paneGlassColorless>, <ore:paneGlassColorless>], [<sevendaystomine:photo_cell>, <sevendaystomine:photo_cell>, <sevendaystomine:photo_cell>], [<ore:ingotIron>, <openmodularturrets:intermediate_regular:0>, <ore:ingotIron>]]);
recipes.addShaped("loot_dropper", <openmodularturrets:addon_meta:7>, [[<quark:biotite_block>, <minecraft:hopper>, <quark:biotite_block>], [<minecraft:dropper>, <techguns:itemshared:70>, <ore:circuitElite>], [<quark:biotite_block>, <openmodularturrets:intermediate_regular:0>, <quark:biotite_block>]]);
recipes.addShaped("accuracy", <openmodularturrets:upgrade_meta:0>, [[<techguns:itemshared:57>, <minecraft:ender_eye>, <techguns:itemshared:57>], [<sevendaystomine:gear>, <techguns:itemshared:57>, <sevendaystomine:gear>], [<ore:plateIron>, <openmodularturrets:intermediate_regular:0>, <ore:plateIron>]]);
recipes.addShaped("efficency", <openmodularturrets:upgrade_meta:1>, [[<ore:nuggetGold>, <ore:wireGold>, <ore:nuggetGold>], [<ore:itemRubber>, <techguns:itemshared:125>, <ore:itemRubber>], [<ore:itemRubber>, <openmodularturrets:intermediate_regular:0>, <ore:itemRubber>]]);
recipes.addShaped("fire_rate", <openmodularturrets:upgrade_meta:2>, [[<techguns:itemshared:38>, null, <techguns:itemshared:38>], [<minecraft:blaze_powder>, <techguns:itemshared:58>, <minecraft:blaze_powder>], [null, <openmodularturrets:intermediate_regular:0>, null]]);
recipes.addShaped("range", <openmodularturrets:upgrade_meta:3>, [[<ore:gemDiamond>, <ore:paneGlassColorless>, <ore:gemDiamond>], [<spartanweaponry:material:2>, <spartanweaponry:material:2>, <spartanweaponry:material:2>], [<ore:blockLead>, <openmodularturrets:intermediate_regular:0>, <ore:blockLead>]]);
recipes.addShaped("spread", <openmodularturrets:upgrade_meta:4>, [[null, <minecraft:flint>, null], [<minecraft:flint>, <spartanweaponry:material:2>, <minecraft:flint>], [<ore:blockLead>, <openmodularturrets:intermediate_regular:0>, <ore:blockLead>]]);
recipes.addShaped("turret_base_tier_1", <openmodularturrets:turret_base:0>, [[<ore:stonesCobble>, <ore:plankWood>, <ore:stonesCobble>], [<ore:plankWood>, <openmodularturrets:intermediate_tiered:0>, <ore:plankWood>], [<ore:stonesCobble>, <ore:plankWood>, <ore:stonesCobble>]]);
recipes.addShaped("turret_base_tier_4", <openmodularturrets:turret_base:3>, [[<netherex:rime_crystal>, <openmodularturrets:turret_base:2>, <netherex:rime_crystal>], [<openmodularturrets:intermediate_regular:0>, <openmodularturrets:intermediate_tiered:3>, <openmodularturrets:intermediate_regular:0>], [<netherex:rime_crystal>, <openmodularturrets:intermediate_regular:0>, <netherex:rime_crystal>]]);
recipes.addShaped("turret_base_tier_5", <openmodularturrets:turret_base:4>, [[<quark:duskbound_block>, <openmodularturrets:turret_base:3>, <quark:duskbound_block>], [<openmodularturrets:intermediate_regular:0>, <openmodularturrets:intermediate_tiered:4>, <openmodularturrets:intermediate_regular:0>], [<quark:duskbound_block>, <openmodularturrets:intermediate_regular:0>, <quark:duskbound_block>]]);
recipes.addShaped("inventory_expander_1", <openmodularturrets:expander:0>, [[<ore:stonesCobble>, <ore:plankWood>, <ore:stonesCobble>], [<openmodularturrets:intermediate_regular:0>, <ore:chestWood>, <openmodularturrets:intermediate_regular:0>], [<ore:stonesCobble>, <openmodularturrets:intermediate_regular:0>, <ore:stonesCobble>]]);
recipes.addShaped("inventory_expander_4", <openmodularturrets:expander:3>, [[<netherex:rime_crystal>, <openmodularturrets:expander:2>, <netherex:rime_crystal>], [<openmodularturrets:intermediate_regular:0>, <ore:chestWood>, <openmodularturrets:intermediate_regular:0>], [<netherex:rime_crystal>, <openmodularturrets:intermediate_regular:0>, <netherex:rime_crystal>]]);
recipes.addShaped("inventory_expander_5", <openmodularturrets:expander:4>, [[<quark:duskbound_block>, <openmodularturrets:expander:3>, <quark:duskbound_block>], [<openmodularturrets:intermediate_regular>, <ore:chestWood>, <openmodularturrets:intermediate_regular>], [<quark:duskbound_block>, <openmodularturrets:intermediate_regular>, <quark:duskbound_block>]]);
recipes.addShaped("power_capasity_1", <openmodularturrets:expander:5>, [[<ore:stonesCobble>, <ore:plankWood>, <ore:stonesCobble>], [<openmodularturrets:intermediate_regular:0>, <ore:dustRedstone>, <openmodularturrets:intermediate_regular:0>], [<ore:stonesCobble>, <openmodularturrets:intermediate_regular:0>, <ore:stonesCobble>]]);
recipes.addShaped("power_capasity_4", <openmodularturrets:expander:8>, [[<netherex:rime_crystal>, <openmodularturrets:expander:7>, <netherex:rime_crystal>], [<openmodularturrets:intermediate_regular:0>, <ore:blockRedstone>, <openmodularturrets:intermediate_regular:0>], [<netherex:rime_crystal>, <openmodularturrets:intermediate_regular:0>, <netherex:rime_crystal>]]);
recipes.addShaped("power_capasity_5", <openmodularturrets:expander:9>, [[<quark:duskbound_block>, <openmodularturrets:expander:8>, <quark:duskbound_block>], [<openmodularturrets:intermediate_regular:0>, <ore:blockRedstone>, <openmodularturrets:intermediate_regular:0>], [<quark:duskbound_block>, <openmodularturrets:intermediate_regular:0>, <quark:duskbound_block>]]);
recipes.addShaped("loot_deleter", <openmodularturrets:base_addon:0>, [[<quark:duskbound_block>, <ore:ingotIron>, <quark:duskbound_block>], [<openmodularturrets:intermediate_regular:0>, <ore:dustRedstone>, <openmodularturrets:intermediate_regular:0>], [<quark:duskbound_block>, <openmodularturrets:intermediate_regular:0>, <quark:duskbound_block>]]);
recipes.addShaped("trash_turret", <openmodularturrets:disposable_item_turret>, [[null, <openmodularturrets:intermediate_tiered:10>, null], [<ore:stonesCobble>, <openmodularturrets:intermediate_tiered:5>, <ore:stonesCobble>], [<ore:stonesCobble>, <ore:dustRedstone>, <ore:stonesCobble>]]);
recipes.addShaped("potato_turret", <openmodularturrets:potato_cannon_turret>, [[<ore:stonesCobble>, <openmodularturrets:intermediate_tiered:10>, <ore:stonesCobble>], [<ore:stonesCobble>, <openmodularturrets:intermediate_tiered:10>, <ore:stonesCobble>], [<ore:dustRedstone>, <openmodularturrets:intermediate_tiered:5>, <ore:dustRedstone>]]);
recipes.addShaped("rocket_launcher", <openmodularturrets:rocket_turret>, [[<ore:gemQuartz>, <openmodularturrets:intermediate_tiered:13>, <ore:gemQuartz>], [<openmodularturrets:intermediate_tiered:13>, <openmodularturrets:intermediate_tiered:8>, <openmodularturrets:intermediate_tiered:13>], [<netherex:rime_crystal>, <openmodularturrets:intermediate_regular:0>, <netherex:rime_crystal>]]);
recipes.addShaped("teleporter_turret", <openmodularturrets:teleporter_turret>, [[<minecraft:ender_eye>, <ore:gemQuartz>, <minecraft:ender_eye>], [<netherex:rime_crystal>, <openmodularturrets:intermediate_tiered:3>, <netherex:rime_crystal>], [<minecraft:ender_eye>, <openmodularturrets:intermediate_regular:0>, <minecraft:ender_eye>]]);
recipes.addShaped("laser_turret", <openmodularturrets:laser_turret>, [[null, <openmodularturrets:intermediate_tiered:14>, null], [<quark:duskbound_block>, <openmodularturrets:intermediate_tiered:9>, <quark:duskbound_block>], [<openmodularturrets:intermediate_regular:0>, <quark:duskbound_block>, <openmodularturrets:intermediate_regular:0>]]);
recipes.addShaped("rail_gun", <openmodularturrets:rail_gun_turret>, [[<quark:duskbound_block>, <openmodularturrets:intermediate_tiered:14>, <quark:duskbound_block>], [<quark:duskbound_block>, <openmodularturrets:intermediate_tiered:14>, <quark:duskbound_block>], [<openmodularturrets:intermediate_regular:0>, <openmodularturrets:intermediate_tiered:9>, <openmodularturrets:intermediate_regular:0>]]);
recipes.addShapedMirrored("turret_crank", <openmodularturrets:lever_block>, [[<ore:stonesCobble>, <ore:stonesCobble>, <ore:stonesCobble>], [<ore:stonesCobble>, null, null], [<ore:stonesCobble>, null, null]]);
recipes.addShapeless("grenades_from_frag", <openmodularturrets:ammo_meta:3>, [<techguns:fraggrenade>]);
recipes.addShapeless("grenades_from_stiel", <openmodularturrets:ammo_meta:3>, [<techguns:stielgranate>]);
recipes.addShapeless(<openmodularturrets:disposable_item_turret>, [<sevendaystomine:turret_base>]);
recipes.addShapeless(<openmodularturrets:machine_gun_turret>, [<sevendaystomine:turret_advanced>]);																																																										 
//============================================================================================================================================================================================
//NETHEREX
recipes.addShapeless("chunk_to_sliver", <netherex:bone_sliver>, [<netherex:bone_chunk>, <netherex:bone_chunk>]);
recipes.addShapeless("rime_steel", <netherex:rime_and_steel>, [<ore:ingotSteel>, <minecraft:flint>, <netherex:rime_crystal>]);
recipes.addShaped("dull_mirror", <netherex:dull_mirror>, [[<netherex:ghast_queen_tear>, <ore:ingotGold>, <netherex:ghast_queen_tear>]]);
recipes.addShapeless("hyphae", <netherex:hyphae>, [<minecraft:mycelium>, <netherex:spore>]);
recipes.addShapeless("blazed_bones_from_lantern", <netherex:blazed_wither_bone> * 6, [<quark:blaze_lantern>]);
recipes.addShaped("obsidian_boat", <netherex:obsidian_boat>, [[<ore:plateObsidianSteel>, null, <ore:plateObsidianSteel>], [<ore:ingotObsidianSteel>, <ore:blockObsidianSteel>, <ore:ingotObsidianSteel>]]);
//============================================================================================================================================================================================
//OCEANIC EXPANSE
recipes.addShaped("heavy_boots", <oe:heavy_boots>, [[<ore:ingotObsidianSteel>, null, <ore:ingotObsidianSteel>], [<ore:ingotObsidianSteel>, null, <ore:ingotObsidianSteel>]]);
recipes.addShapeless("palm_bark_from_logs", <oe:palm_wood> * 9, [<oe:palm_log>, <oe:palm_log>, <oe:palm_log>, <oe:palm_log>, <oe:palm_log>, <oe:palm_log>, <oe:palm_log>, <oe:palm_log>, <oe:palm_log>]);
recipes.addShapeless("palm_logs_from_bark", <oe:palm_log>, * 9, [<oe:palm_wood>, <oe:palm_wood>, <oe:palm_wood>, <oe:palm_wood>, <oe:palm_wood>, <oe:palm_wood>, <oe:palm_wood>, <oe:palm_wood>, <oe:palm_wood>]);
recipes.addShapeless("stripped_wood_from_logs", <oe:palm_wood_stripped> * 9, [<oe:palm_log_stripped>, <oe:palm_log_stripped>, <oe:palm_log_stripped>, <oe:palm_log_stripped>, <oe:palm_log_stripped>, <oe:palm_log_stripped>, <oe:palm_log_stripped>, <oe:palm_log_stripped>, <oe:palm_log_stripped>]);
recipes.addShapeless("stripped_logs_from_wood", <oe:palm_log_stripped> * 9, [<oe:palm_wood_stripped>, <oe:palm_wood_stripped>, <oe:palm_wood_stripped>, <oe:palm_wood_stripped>, <oe:palm_wood_stripped>, <oe:palm_wood_stripped>, <oe:palm_wood_stripped>, <oe:palm_wood_stripped>, <oe:palm_wood_stripped>]);
//============================================================================================================================================================================================
//CYBERWARE
recipes.addShapeless("radio_beacon", <cyberware:beacon>, [<sevendaystomine:radio>]);
recipes.addShaped("radio_tower", <cyberware:radio_post>, [[<ore:paneIron>, null, <ore:paneIron>], [<ore:paneIron>, <cyberware:component:5>, <ore:paneIron>], [<ore:paneIron>, <cyberware:component:4>, <ore:paneIron>]]);
recipes.addShaped("surgery_machine", <cyberware:surgery>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<ore:ingotIron>, <ore:circuitBasic>, <ore:ingotIron>], [<spartanweaponry:throwing_knife_diamond>, <ore:gearDiamond>, <spartanweaponry:throwing_knife_diamond>]]);
recipes.addShaped("charger", <cyberware:charger>, [[<ore:ingotIron>, <openblocks:xp_drain>, <ore:ingotIron>], [<ore:ingotIron>, <ore:circuitBasic>, <ore:ingotIron>], [<ore:ingotIron>, <ore:dustRedstone>, <ore:ingotIron>]]);
recipes.addShapeless("rotting_bodyparts0", <minecraft:rotten_flesh>, [<cyberware:body_part:0>]);
recipes.addShapeless("rotting_bodyparts1", <minecraft:rotten_flesh>, [<cyberware:body_part:1>]);
recipes.addShapeless("rotting_bodyparts2", <minecraft:rotten_flesh>, [<cyberware:body_part:2>]);
recipes.addShapeless("rotting_bodyparts3", <minecraft:rotten_flesh>, [<cyberware:body_part:3>]);
recipes.addShapeless("rotting_bodyparts4", <minecraft:rotten_flesh>, [<cyberware:body_part:4>]);
recipes.addShapeless("rotting_bodyparts5", <minecraft:rotten_flesh>, [<cyberware:body_part:5>]);
recipes.addShapeless("rotting_bodyparts6", <minecraft:rotten_flesh>, [<cyberware:body_part:6>]);
recipes.addShapeless("rotting_bodyparts7", <minecraft:rotten_flesh>, [<cyberware:body_part:8>]);
recipes.addShapeless("rotting_bodyparts8", <minecraft:rotten_flesh>, [<cyberware:body_part:9>]);
recipes.addShapeless("rotting_bodyparts9", <minecraft:rotten_flesh>, [<cyberware:body_part:10>]);
recipes.addShapeless("rotting_bodyparts10", <minecraft:rotten_flesh>, [<cyberware:body_part:11>]);
recipes.addShapeless("ribs", <minecraft:bone>, [<cyberware:body_part:7>]);
//============================================================================================================================================================================================
//AIR SUPPORT
recipes.addShaped("livestock_remote_0", <air_support:crate_drop_remote>, [[<ore:dustRedstone>, <ore:dyeBlack>, <ore:dustRedstone>], [null, <ore:circuitBasic>, null], [<ore:ingotIron>, <minecraft:stone_button>, <ore:ingotIron>]]);
recipes.addShaped("livestock_remote_1", <air_support:crate_drop_remote>, [[<ore:dustRedstone>, <ore:dyeBlack>, <ore:dustRedstone>], [null, <cyberware:component:3>, null], [<ore:ingotIron>, <minecraft:stone_button>, <ore:ingotIron>]]);
recipes.addShaped("medical_remote_0", <air_support:medical_crate_drop_remote>, [[<ore:dustRedstone>, <ore:dyeWhite>, <ore:dustRedstone>], [null, <ore:circuitBasic>, null], [<ore:ingotIron>, <minecraft:stone_button>, <ore:ingotIron>]]);
recipes.addShaped("medical_remote_1", <air_support:medical_crate_drop_remote>, [[<ore:dustRedstone>, <ore:dyeWhite>, <ore:dustRedstone>], [null, <cyberware:component:3>, null], [<ore:ingotIron>, <minecraft:stone_button>, <ore:ingotIron>]]);
recipes.addShaped("utility_remote_0", <air_support:utility_crate_drop_remote>, [[<ore:dustRedstone>, <ore:dyeBlue>, <ore:dustRedstone>], [null, <ore:circuitBasic>, null], [<ore:ingotIron>, <minecraft:stone_button>, <ore:ingotIron>]]);
recipes.addShaped("utility_remote_1", <air_support:utility_crate_drop_remote>, [[<ore:dustRedstone>, <ore:dyeBlue>, <ore:dustRedstone>], [null, <cyberware:component:3>, null], [<ore:ingotIron>, <minecraft:stone_button>, <ore:ingotIron>]]);
//============================================================================================================================================================================================
//FTB QUEST
recipes.addShapeless("quest_book", <ftbquests:book>, [<ore:stones>, <ftbquests:book>]);
recipes.addShaped("Tasks_screen_1x1", <ftbquests:screen>, [[<ore:stones>, <ore:stones>, <ore:stones>], [<ore:stones>, <ftbquests:book>, <ore:stones>], [<ore:stones>, <ore:stones>, <ore:stones>]]);
recipes.addShapedMirrored("task_screen_5x5", <ftbquests:screen>.withTag({BlockEntityTag: {Size: 2 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}), [[<ftbquests:screen>.withTag({BlockEntityTag: {Size: 1 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}), <ftbquests:screen>, <ftbquests:screen>], [<ftbquests:screen>, <ftbquests:screen>.withTag({BlockEntityTag: {Size: 1 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}), <ftbquests:screen>], [<ftbquests:screen>, <ftbquests:screen>, <ftbquests:screen>.withTag({BlockEntityTag: {Size: 1 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}})]]);
recipes.addShapedMirrored("task_screen_7x7", <ftbquests:screen>.withTag({BlockEntityTag: {Size: 3 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}), [[<ftbquests:screen>.withTag({BlockEntityTag: {Size: 2 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}), <ftbquests:screen>, <ftbquests:screen>], [<ftbquests:screen>, <ftbquests:screen>.withTag({BlockEntityTag: {Size: 2 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}), <ftbquests:screen>], [<ftbquests:screen>, <ftbquests:screen>, <ftbquests:screen>.withTag({BlockEntityTag: {Size: 2 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}})]]);
recipes.addShapedMirrored("task_screen_9x9", <ftbquests:screen>.withTag({BlockEntityTag: {Size: 4 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}), [[<ftbquests:screen>.withTag({BlockEntityTag: {Size: 3 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}), <ftbquests:screen>, <ftbquests:screen>], [<ftbquests:screen>, <ftbquests:screen>.withTag({BlockEntityTag: {Size: 3 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}), <ftbquests:screen>], [<ftbquests:screen>, <ftbquests:screen>, <ftbquests:screen>.withTag({BlockEntityTag: {Size: 3 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}})]]);
recipes.addShapedMirrored("progress_screen_5x5", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 4 as byte, id: "ftbquests:progress_screen_core", Width: 2 as byte}, display: {Lore: ["(+NBT)"]}}), [[<ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 2 as byte, id: "ftbquests:progress_screen_core", Width: 1 as byte}, display: {Lore: ["(+NBT)"]}}), <ftbquests:progress_screen>, <ftbquests:progress_screen>], [<ftbquests:progress_screen>, <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 2 as byte, id: "ftbquests:progress_screen_core", Width: 1 as byte}, display: {Lore: ["(+NBT)"]}}), <ftbquests:progress_screen>], [<ftbquests:progress_screen>, <ftbquests:progress_screen>, <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 2 as byte, id: "ftbquests:progress_screen_core", Width: 1 as byte}, display: {Lore: ["(+NBT)"]}})]]);
recipes.addShapedMirrored("progress_screen_7x7", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 6 as byte, id: "ftbquests:progress_screen_core", Width: 3 as byte}, display: {Lore: ["(+NBT)"]}}), [[<ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 4 as byte, id: "ftbquests:progress_screen_core", Width: 2 as byte}, display: {Lore: ["(+NBT)"]}}), <ftbquests:progress_screen>, <ftbquests:progress_screen>], [<ftbquests:progress_screen>, <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 4 as byte, id: "ftbquests:progress_screen_core", Width: 2 as byte}, display: {Lore: ["(+NBT)"]}}), <ftbquests:progress_screen>], [<ftbquests:progress_screen>, <ftbquests:progress_screen>, <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 4 as byte, id: "ftbquests:progress_screen_core", Width: 2 as byte}, display: {Lore: ["(+NBT)"]}})]]);
recipes.addShapedMirrored("progress_screen_9x9", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 8 as byte, id: "ftbquests:progress_screen_core", Width: 4 as byte}, display: {Lore: ["(+NBT)"]}}), [[<ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 6 as byte, id: "ftbquests:progress_screen_core", Width: 3 as byte}, display: {Lore: ["(+NBT)"]}}), <ftbquests:progress_screen>, <ftbquests:progress_screen>], [<ftbquests:progress_screen>, <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 6 as byte, id: "ftbquests:progress_screen_core", Width: 3 as byte}, display: {Lore: ["(+NBT)"]}}), <ftbquests:progress_screen>], [<ftbquests:progress_screen>, <ftbquests:progress_screen>, <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 6 as byte, id: "ftbquests:progress_screen_core", Width: 3 as byte}, display: {Lore: ["(+NBT)"]}})]]);
//============================================================================================================================================================================================
//CHISEL
recipes.addShaped("Auto_chisel", <chisel:auto_chisel>, [[<ore:blockGlass>, <ore:blockGlass, <ore:blockGlass>], [<ore:blockGlass>, <chisel:chisel_iron>, <ore:blockGlass>], [<ore:chiseled_stone_brick>, <ore:dustRedstone>, <ore:chiseled_stone_brick>]]);

