#priority 5
// File created by Nykrdaudr
//Crafting table recipes
//TECHGUNS


//============================================================================================================================================================================================
recipes.addShaped("uv_emitter_0", <techguns:itemshared:105>, [[<ore:circuitElite>, <ore:wireGold>, <ore:circuitElite>], [<ore:plateCarbon>, <minecraft:redstone_lamp>, <ore:plateCarbon>], [<ore:plateCarbon>, <netherex:amethyst_block>, <ore:plateCarbon>]]);
recipes.addShaped("heavy_cloth", <techguns:itemshared:60>, [[null, <ore:wool>, null], [<ore:wool>, <ore:leather>, <ore:wool>], [null, <ore:wool>, null]]);
recipes.addShaped("machine_stack_upgrade", <techguns:itemshared:94>, [[<ore:plateIron>, <ore:dyeGreen>, <ore:plateIron>], [<ore:ingotGold>, <ore:chestWood>, <ore:ingotGold>], [<ore:plateIron>, <ore:ingotGold>, <ore:plateIron>]]);
recipes.addShaped("ore_drill_engine", <techguns:oredrill:3> * 2, [[<ore:paneIron>, <ore:paneIron>, <ore:paneIron>], [<ore:paneIron>, <techguns:itemshared:70>, <ore:paneIron>], [<ore:paneIron>, <ore:paneIron>, <ore:paneIron>]]);
recipes.addShaped("ore_drill_scaffold", <techguns:oredrill:1> * 4, [[<ore:paneIron>, <ore:paneIron>, <ore:paneIron>], [<ore:paneIron>, <ore:plateIron>, <ore:paneIron>], [<ore:paneIron>, <ore:paneIron>, <ore:paneIron>]]);
recipes.addShaped("ore_drill_frame", <techguns:oredrill:0> * 4, [[<ore:plateIron>, <ore:paneIron>, <ore:plateIron>], [<ore:paneIron>, <ore:plateIron>, <ore:paneIron>], [<ore:plateIron>, <ore:paneIron>, <ore:plateIron>]]);
//============================================================================================================================================================================================
//BLOCKS
recipes.addShaped("chem_lab", <techguns:basicmachine:2>, [[<ore:ingotIron>, <sevendaystomine:emptyjar>, <ore:ingotIron>], [<sevendaystomine:emptyjar>, <techguns:itemshared:70>, <sevendaystomine:emptyjar>], [<ore:ingotIron>, <ore:dustRedstone>, <ore:ingotIron>]]);
recipes.addShaped("iron_ladder", <techguns:ladder0:8> * 3, [[<minecraft:iron_nugget>, null, <minecraft:iron_nugget>], [<minecraft:iron_nugget>, <minecraft:iron_nugget>, <minecraft:iron_nugget>], [<minecraft:iron_nugget>, null, <minecraft:iron_nugget>]]);
recipes.addShaped("quartz_ladder", <techguns:ladder0:9> * 3, [[<techguns:itemshared:103>, null, <techguns:itemshared:103>], [<techguns:itemshared:103>, <techguns:itemshared:103>, <techguns:itemshared:103>], [<techguns:itemshared:103>, null, <techguns:itemshared:103>]]);
recipes.addShaped("steel_ladder", <techguns:ladder0:11> * 3, [[<ore:nuggetSteel>, null, <ore:nuggetSteel>], [<ore:nuggetSteel>, <ore:nuggetSteel>, <ore:nuggetSteel>], [<ore:nuggetSteel>, null, <ore:nuggetSteel>]]);
recipes.addShaped("slime_ladder", <techguns:slimyladder:3> * 3, [[<minecraft:slime_ball>], [<minecraft:slime_ball>], [<minecraft:slime_ball>]]);
recipes.addShaped("neon_lights", <techguns:neonlights:0>,  [[<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>], [<ore:paneGlass>, <minecraft:glowstone_dust>, <ore:paneGlass>], [<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>]]);
recipes.addShaped("lamps", <techguns:lamp0:0> * 3, [[<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>], [<ore:paneGlass>, <quark:lit_lamp>, <ore:paneGlass>], [<ore:paneGlass>, <ore:paneGlass>, <ore:paneGlass>]]);
recipes.addShaped("lantern", <techguns:lamp0:12> * 3, [[<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>], [<ore:paneGlass>, <quark:lit_lamp>, <ore:paneGlass>], [<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>]]);
recipes.addShaped("door_3x3", <techguns:item_door3x3:0>, [[<ore:plateSteel>, <techguns:itemshared:70>, <ore:plateSteel>], [<minecraft:piston>, <ore:plateSteel>, <minecraft:piston>], [<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>]]);
recipes.addShaped("door_up", <techguns:item_door3x3:1>, [[<minecraft:piston>, <techguns:itemshared:70>, <minecraft:piston>], [<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>], [<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>]]);
recipes.addShaped("door_down", <techguns:item_door3x3:2>, [[<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>], [<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>], [<minecraft:piston>, <techguns:itemshared:70>, <minecraft:piston>]]);
recipes.addShaped("nether_door", <techguns:item_door3x3:3> * 3, [[<techguns:itemshared:76>, <ore:nether_metal>, <techguns:itemshared:76>], [<techguns:itemshared:70>, <ore:nether_metal>, <techguns:itemshared:70>], [<techguns:itemshared:76>, <ore:nether_metal>, <techguns:itemshared:76>]]);
recipes.addShaped("camonet_roof", <techguns:camonet_top> * 6, [[<minecraft:stick>, <ore:treeLeaves>, <minecraft:stick>], [<pvj:mud>, <minecraft:string>, <pvj:mud>], [<minecraft:stick>, <ore:treeLeaves>, <minecraft:stick>]]);
recipes.addShaped("camonet_wall", <techguns:camonet> * 6, [[<minecraft:stick>, <ore:treeLeaves>, <minecraft:stick>], [<minecraft:stick>, <pvj:mud>, <minecraft:stick>]]);
recipes.addShaped("blast_furnace_1", <techguns:simplemachine:11>, [[<ore:plateIron>, <ore:dustRedstone>, <ore:plateIron>], [<ore:plateIron>, <minecraft:furnace>, <ore:plateIron>], [<ore:stone_brick>, <ore:blockIron>, <ore:stone_brick>]]);
recipes.addShaped("upgrade_bench", <techguns:simplemachine2:9>, [[null, <ore:craftingTable>, null], [<ore:plateObsidianSteel>, <ore:gemEmerald>, <ore:plateObsidianSteel>], [<minecraft:obsidian>, <ore:plateObsidianSteel>, <minecraft:obsidian>]]);
//============================================================================================================================================================================================
//FROM MODS
recipes.addShaped("worn_ladder", <techguns:ladder0:10> * 3, [[<sevendaystomine:scrapiron>, null, <sevendaystomine:scrapiron>], [<sevendaystomine:scrapiron>, <sevendaystomine:scrapiron>, <sevendaystomine:scrapiron>], [<sevendaystomine:scrapiron>, null, <sevendaystomine:scrapiron>]]);
recipes.addShaped("blast_furnace_0", <techguns:simplemachine:11>, [[<ore:plateIron>, <ore:dustRedstone>, <ore:plateIron>], [<ore:plateIron>, <sevendaystomine:forge>, <ore:plateIron>], [<ore:stone_brick>, <ore:blockIron>, <ore:stone_brick>]]);
recipes.addShaped("heatray_focus", <techguns:itemshared:104>, [[<ore:circuitElite>, <ore:wireGold>, <ore:circuitElite>], [<ore:plateSteel>, <quark:lit_lamp>, <ore:plateSteel>], [<ore:plateSteel>, <quark:lit_lamp>, <ore:plateSteel>]]);
recipes.addShaped("uv_emitter_1", <techguns:itemshared:105>, [[<ore:circuitElite>, <ore:wireGold>, <ore:circuitElite>], [<ore:plateCarbon>, <quark:lit_lamp>, <ore:plateCarbon>], [<ore:plateCarbon>, <netherex:amethyst_block>, <ore:plateCarbon>]]);
recipes.addShapeless("gas_can_to_fuel", <techguns:itemshared:27>, [<sevendaystomine:gas_canister>]);
recipes.addShapeless("hdd_to_cybernetics", <techguns:itemshared:69> * 3, [<sevendaystomine:hdd>]);
recipes.addShaped("reaction_chamber_glass", <techguns:multiblockmachine:4> * 6, [[<techguns:multiblockmachine:3>, <quark:framed_glass>, <techguns:multiblockmachine:3>], [<techguns:multiblockmachine:3>, <quark:framed_glass>, <techguns:multiblockmachine:3>], [<techguns:multiblockmachine:3>, <quark:framed_glass>, <techguns:multiblockmachine:3>]]);
recipes.addShaped("reaction_chamber_controller", <techguns:multiblockmachine:5>, [[null, <netherex:soul_glass>, null], [<ore:circuitElite>, <techguns:multiblockmachine:3>, <ore:circuitElite>], [null, <netherex:soul_glass>, null]]);
recipes.addShaped("stick_granates", <techguns:stielgranate> * 16, [[null, <ore:ingotIron>, <minecraft:tnt>], [null, <spartanweaponry:material:0>, <ore:ingotIron>], [<ore:ingotIron>, null, null]]);
recipes.addShaped("bunker_door", <parasitusfix:door_bunker>, [[<ore:plateIron>, <ore:plateIron>], [<ore:plateIron>, <ore:plateIron>], [<ore:plateIron>, <ore:plateIron>]]);
//============================================================================================================================================================================================
//ARMOR, WEAPONS AND AMMO
recipes.addShaped("stone_barrel", <techguns:itemshared:37>, [[<minecraft:stone_slab:0>, <minecraft:stone_slab:0>, <minecraft:stone_slab:0>], [null, null, null], [<minecraft:stone_slab:0>, <minecraft:stone_slab:0>, <minecraft:stone_slab:0>]]);
recipes.addShaped("riot_shield", <techguns:riot_shield>, [[<ore:ingotSteel>, <ore:paneGlassColorless>, <ore:ingotSteel>], [<ore:ingotSteel>, <minecraft:shield>, <ore:ingotSteel>], [<ore:ingotSteel>, <ore:paneGlassColorless>, <ore:ingotSteel>]]);
recipes.addShaped("ballistic_shield", <techguns:ballistic_shield>, [[<ore:plateObsidianSteel>, <ore:paneGlassColorless>, <ore:plateObsidianSteel>], [<ore:plateObsidianSteel>, <minecraft:shield>, <ore:plateObsidianSteel>], [<ore:plateObsidianSteel>, <ore:plateObsidianSteel>, <ore:plateObsidianSteel>]]);
recipes.addShaped("advanced_shield", <techguns:advanced_shield>, [[<ore:plateCarbon>, <ore:paneGlassColorless>, <ore:plateCarbon>], [<ore:plateCarbon>, <minecraft:shield>, <ore:plateCarbon>], [<ore:plateCarbon>, <ore:plateCarbon>, <ore:plateCarbon>]]);
recipes.addShaped("gas_mask_0", <techguns:gasmask>, [[<ore:paneGlassColorless>, <ore:itemRubber>, <ore:paneGlassColorless>], [<ore:itemRubber>, <ore:itemRubber>, <ore:itemRubber>], [<ore:itemRubber>, <techguns:itemshared:89>, <ore:itemRubber>]]);
recipes.addShaped("gas_mask_1", <techguns:gasmask>, [[<ore:paneGlassLightGray>, <ore:itemRubber>, <ore:paneGlassLightGray>], [<ore:itemRubber>, <ore:itemRubber>, <ore:itemRubber>], [<ore:itemRubber>, <techguns:itemshared:89>, <ore:itemRubber>]]);
recipes.addShaped("mining_charge", <techguns:explosive_charge> * 4, [[<ore:itemRubber>, <minecraft:tnt>, <ore:itemRubber>], [<minecraft:tnt>, <ore:circuitBasic>, <minecraft:tnt>], [<ore:itemRubber>, <minecraft:tnt>, <ore:itemRubber>]]);
recipes.addShaped("jumppack_0", <techguns:jumppack:999>, [[<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:plateIron>, <techguns:itemshared:90>, <ore:plateIron>], [<techguns:itemshared:24>, null, <techguns:itemshared:24>]]);
recipes.addShaped("oxygen_tank_0", <techguns:scubatanks:599>, [[<ore:sheetPlastic>, null, <ore:sheetPlastic>], [<techguns:itemshared:24>, <ore:plateIron>, <techguns:itemshared:24>], [<ore:sheetPlastic>, null, <ore:sheetPlastic>]]);

recipes.addShaped("grim_reaper_1", <techguns:grimreaper>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[<techguns:guidedmissilelauncher>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), <techguns:guidedmissilelauncher>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte})], [<techguns:guidedmissilelauncher>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), <techguns:guidedmissilelauncher>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), <techguns:itemshared:36>]]);
recipes.addShaped("golden_revolver_1", <techguns:goldenrevolver>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:ingotGold>, <ore:ingotGold>, <ore:ingotGold>], [<ore:ingotGold>, <techguns:revolver>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), <ore:ingotGold>], [<ore:ingotGold>, <ore:ingotGold>, <ore:ingotGold>]]);
recipes.addShaped("vector_0", <techguns:vector>.withTag({ammo: 25 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:39>, <techguns:itemshared:35>, <techguns:itemshared:43>], [null, <techguns:itemshared:9>, null]]);
recipes.addShaped("vector_1", <techguns:vector>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:39>, <techguns:itemshared:35>, <techguns:itemshared:43>], [null, <techguns:itemshared:10>, null]]);
recipes.addShaped("m4_0", <techguns:m4>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:39>, <techguns:itemshared:34>, <techguns:itemshared:43>], [<ore:nuggetIron>, <techguns:itemshared:13>, <ore:ingotIron>]]);
recipes.addShaped("m4_1", <techguns:m4>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:39>, <techguns:itemshared:34>, <techguns:itemshared:43>], [<ore:nuggetIron>, <techguns:itemshared:14>, <ore:ingotIron>]]);
recipes.addShaped("lmg_0", <techguns:lmg>.withTag({ammo: 100 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:39>, <techguns:itemshared:35>, <techguns:itemshared:43>], [null, <techguns:itemshared:15>, null]]);
recipes.addShaped("lmg_1", <techguns:lmg>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:39>, <techguns:itemshared:35>, <techguns:itemshared:43>], [null, <techguns:itemshared:16>, null]]);
recipes.addShaped("aug_0", <techguns:aug>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:paneGlassColorless>, <ore:plateSteel>, <ore:paneGlassColorless>], [<techguns:itemshared:39>, <techguns:itemshared:34>, <techguns:itemshared:43>], [<ore:sheetPlastic>, null, <techguns:itemshared:13>]]);
recipes.addShaped("aug_1", <techguns:aug>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:paneGlassColorless>, <ore:plateSteel>, <ore:paneGlassColorless>], [<techguns:itemshared:39>, <techguns:itemshared:34>, <techguns:itemshared:43>], [<ore:sheetPlastic>, null, <techguns:itemshared:14>]]);
recipes.addShaped("m4_alt_0", <techguns:m4_infiltrator>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:blockGlassColorless>, <ore:plateSteel>, <ore:blockGlassColorless>], [<ore:blockWool>, <ore:blockWool>, <techguns:m4>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte})], [<ore:dustRedstone>, <ore:dustRedstone>, <ore:ingotSteel>]]);
recipes.addShaped("m4_alt_1", <techguns:m4_infiltrator>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:blockGlassColorless>, <ore:plateSteel>, <ore:blockGlassColorless>], [<ore:blockWool>, <ore:blockWool>, <techguns:m4>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte})], [<ore:dustRedstone>, <ore:dustRedstone>, <ore:ingotSteel>]]);
recipes.addShaped("bolt_action_rifle_0", <techguns:boltaction>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:blockGlassColorless>, <ore:plateIron>, null], [<techguns:itemshared:39>, <techguns:itemshared:33>, <techguns:itemshared:42>]]);
recipes.addShaped("bolt_action_rifle_1", <techguns:boltaction>.withTag({ammo: 6 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:blockGlassColorless>, <ore:plateIron>, null], [<techguns:itemshared:39>, <techguns:itemshared:33>, <techguns:itemshared:42>], [null, <techguns:itemshared:3>, null]]);
recipes.addShaped("scar_0", <techguns:scar>.withTag({ammo: 20 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:blockGlassColorless>, <ore:sheetPlastic>, <ore:gemDiamond>], [<techguns:itemshared:39>, <techguns:itemshared:35>, <techguns:itemshared:43>], [null, <techguns:itemshared:13>, null]]);
recipes.addShaped("scar_1", <techguns:scar>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:blockGlassColorless>, <ore:sheetPlastic>, <ore:gemDiamond>], [<techguns:itemshared:39>, <techguns:itemshared:35>, <techguns:itemshared:43>], [null, <techguns:itemshared:14>, null]]);
recipes.addShaped("guided_missile_launcher_0", <techguns:guidedmissilelauncher>.withTag({ammo: 1 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:blockGlassColorless>, <ore:circuitElite>], [<techguns:itemshared:7>, <techguns:itemshared:39>, <techguns:itemshared:39>], [null, <techguns:itemshared:35>, null]]);
recipes.addShaped("guided_missile_launcher_1", <techguns:guidedmissilelauncher>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:blockGlassColorless>, <ore:circuitElite>], [<techguns:itemshared:39>, <techguns:itemshared:39>], [<techguns:itemshared:35>, null]]);
recipes.addShaped("tesla_0", <techguns:teslagun>.withTag({ammo: 25 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:68>, <techguns:itemshared:36>, <techguns:itemshared:44>], [null, <techguns:itemshared:29>, null]]);
recipes.addShaped("tesla_1", <techguns:teslagun>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:68>, <techguns:itemshared:36>, <techguns:itemshared:44>], [null, <techguns:itemshared:30>, null]]);
recipes.addShaped("gauss_0", <techguns:gaussrifle>.withTag({ammo: 8 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:gemDiamond>, <ore:plateTitanium>, <ore:circuitElite>], [<techguns:itemshared:128>, <techguns:itemshared:36>, <techguns:itemshared:44>], [null, <techguns:itemshared:127>, <techguns:itemshared:29>]]);
recipes.addShaped("gauss_1", <techguns:gaussrifle>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:gemDiamond>, <ore:plateTitanium>, <ore:circuitElite>], [<techguns:itemshared:128>, <techguns:itemshared:36>, <techguns:itemshared:44>], [null, null, <techguns:itemshared:30>]]);

recipes.addShaped("stone_bullets", <techguns:itemshared:0> * 8, [[<sevendaystomine:smallstone>, <sevendaystomine:smallstone>, <sevendaystomine:smallstone>], [<sevendaystomine:smallstone>, <minecraft:gunpowder>, <sevendaystomine:smallstone>], [<sevendaystomine:smallstone>, <sevendaystomine:smallstone>, <sevendaystomine:smallstone>]]);
recipes.addShaped("pistol_rounds", <techguns:itemshared:1> * 3, [[<ore:nuggetCopper>, <ore:ingotLead>, <ore:nuggetCopper>], [<ore:nuggetCopper>, <minecraft:gunpowder>, <ore:nuggetCopper>], [<ore:nuggetCopper>, <ore:nuggetCopper>, <ore:nuggetCopper>]]);
recipes.addShaped("shotgun_bullets", <techguns:itemshared:2> * 3, [[<ore:nuggetLead>, <ore:nuggetLead>, <ore:nuggetLead>],  [<ore:nuggetCopper>, <minecraft:gunpowder>, <ore:nuggetCopper>], [<ore:nuggetCopper>, <ore:nuggetCopper>, <ore:nuggetCopper>]]);
recipes.addShaped("rocket", <techguns:itemshared:7>, [[null, <ore:nuggetIron>, null], [<ore:plateIron>, <minecraft:tnt>, <ore:plateIron>], [<ore:plateIron>, <minecraft:gunpowder>, <ore:plateIron>]]);
recipes.addShapeless("smg_magazine_loaded", <techguns:itemshared:9>, [<techguns:itemshared:10>, <techguns:itemshared:1>, <techguns:itemshared:1>, <techguns:itemshared:1>]);
recipes.addShaped("smg_magazine2", <techguns:itemshared:10>, [[<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:nuggetIron>, <techguns:itemshared:57>, <ore:nuggetIron>]]);
recipes.addShaped("pistol_magazine", <techguns:itemshared:12>, [[<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:nuggetIron>, <techguns:itemshared:57>, <ore:nuggetIron>], [<ore:nuggetIron>, <ore:ingotIron>, <ore:nuggetIron>]]);
recipes.addShaped("assault_magazine", <techguns:itemshared:14>, [[<ore:nuggetSteel>, null, <ore:nuggetSteel>], [<ore:nuggetSteel>, null, <ore:nuggetSteel>], [<ore:nuggetSteel>, <techguns:itemshared:57>, <ore:nuggetSteel>]]);
recipes.addShapedMirrored("lmg_magazine", <techguns:itemshared:16> * 2, [[null, <ore:ingotSteel>, <ore:ingotSteel>], [<ore:ingotSteel>, <techguns:itemshared:57>, <ore:ingotSteel>], [<ore:ingotSteel>, <ore:ingotSteel>, <ore:ingotSteel>]]);
recipes.addShaped("minigun_drum", <techguns:itemshared:18> * 2, [[<ore:ingotSteel>, <ore:ingotSteel>, <ore:ingotSteel>], [<ore:sheetPlastic>, <techguns:itemshared:58>, <ore:sheetPlastic>], [<ore:ingotSteel>, <ore:ingotSteel>, <ore:ingotSteel>]]);
recipes.addShaped("as50_magazine", <techguns:itemshared:20> * 2, [[<ore:ingotSteel>, null, <ore:ingotSteel>], [<ore:ingotSteel>, null, <ore:ingotSteel>], [<ore:ingotSteel>, <techguns:itemshared:57>, <ore:ingotSteel>]]);
recipes.addShaped("advanced_magazine", <techguns:itemshared:22> * 2, [[<ore:ingotObsidianSteel>, null, <ore:ingotObsidianSteel>], [<ore:ingotObsidianSteel>, null, <ore:ingotObsidianSteel>], [<ore:ingotObsidianSteel>, <techguns:itemshared:58>, <ore:ingotObsidianSteel>]]);
recipes.addShaped("empty_tank1", <techguns:itemshared:24> * 2, [[<ore:plateTin>, <minecraft:lever>, <ore:plateTin>], [<ore:plateTin>, null, <ore:plateTin>], [<ore:plateTin>, <ore:plateTin>, <ore:plateTin>]]);
recipes.addShaped("empty_tank2", <techguns:itemshared:24> * 2, [[<ore:plateIron>, <minecraft:lever>, <ore:plateIron>], [<ore:plateIron>, null, <ore:plateIron>], [<ore:plateIron>, <ore:plateIron>, <ore:plateIron>]]);
recipes.addShaped("fuel", <techguns:itemshared:28>  * 2, [[<ore:sheetPlastic>], [<ore:blockGlass>], [<ore:sheetPlastic>]]);
recipes.addShapeless("smg_fire_magazine", <techguns:itemshared:112>, [<techguns:itemshared:10>, <techguns:itemshared:109>, <techguns:itemshared:109>, <techguns:itemshared:109>]);
recipes.addShaped("nuke", <techguns:itemshared:118>, [[<ore:plateLead>, <ore:circuitBasic>, <ore:plateLead>], [<techguns:itemshared:75>, <ore:ingotUraniumEnriched>, <techguns:itemshared:75>], [<ore:plateLead>, <ore:circuitBasic>, <ore:plateLead>]]);
recipes.addShaped("redstone_battery", <techguns:itemshared:125>, [[<ore:nuggetCopper>, <ore:itemRubber>, <ore:nuggetCopper>], [<ore:plateCopper>, <ore:dustRedstone>, <ore:plateCopper>], [<ore:plateCopper>, <buildcraftsilicon:redstone_chipset:0>, <ore:plateCopper>]]);

recipes.addShaped("commando_helmet", <techguns:t2_commando_helmet>, [[<ore:ingotObsidianSteel>, <ore:itemRubber>, <ore:ingotObsidianSteel>], [<ore:itemRubber>, <ore:paneGlassColorless>, <ore:itemRubber>]]);
recipes.addShaped("power_armor_helmet", <techguns:t3_power_helmet>, [[<ore:circuitElite>, <techguns:itemshared:67>, <ore:circuitElite>], [<techguns:itemshared:67>, <ore:paneGlassColorless>, <techguns:itemshared:67>]]);
recipes.addShaped("hev_helmet", <techguns:t3_miner_helmet>, [[<ore:plateCarbon>, <ore:circuitElite>, <ore:plateCarbon>], [<ore:plateTitanium>, <ore:paneGlassColorless>, <ore:plateTitanium>]]);
recipes.addShaped("nether_combat_boots", <techguns:t4_praetor_boots>, [[null, <techguns:itemshared:70>, null], [<techguns:itemshared:67>, null, <techguns:itemshared:67>], [<ore:plateObsidianSteel>, null, <ore:plateObsidianSteel>]]);
recipes.addShaped("nether_combat_leggings", <techguns:t4_praetor_leggings>, [[<techguns:itemshared:67>, <techguns:itemshared:67>, <techguns:itemshared:67>], [<ore:circuitElite>, null, <ore:circuitElite>], [<ore:plateObsidianSteel>, null, <ore:plateObsidianSteel>]]);
recipes.addShaped("nether_combat_chestplate", <techguns:t4_praetor_chestplate>, [[<techguns:itemshared:70>, <buildcraftfactory:heat_exchange>, <techguns:itemshared:70>], [<techguns:itemshared:67>, <ore:circuitElite>, <techguns:itemshared:67>], [<ore:plateObsidianSteel>, <techguns:itemshared:67>, <ore:plateObsidianSteel>]]);
recipes.addShaped("nether_combat_helmet", <techguns:t4_praetor_helmet>, [[<ore:plateObsidianSteel>, <buildcraftfactory:heat_exchange>, <ore:plateObsidianSteel>], [<techguns:itemshared:67>, <ore:circuitElite>, <techguns:itemshared:67>], [<ore:plateObsidianSteel>, <ore:paneGlassColorless>, <ore:plateObsidianSteel>]]);
recipes.addShaped("power_armor_mk2_boots", <techguns:t4_power_boots>, [[<techguns:itemshared:67>, <techguns:itemshared:59>, <techguns:itemshared:67>], [<techguns:itemshared:102>, <techguns:t3_power_boots>, <techguns:itemshared:102>], [<techguns:itemshared:67>, <ore:plateTitanium>, <techguns:itemshared:67>]]);
recipes.addShaped("power_armor_mk2_leggings", <techguns:t4_power_leggings>, [[<techguns:itemshared:67>, <ore:plateTitanium>, <techguns:itemshared:67>], [<techguns:itemshared:59>, <techguns:t3_power_leggings>, <techguns:itemshared:59>], [<techguns:itemshared:102>, <buildcraftsilicon:redstone_chipset:4>, <techguns:itemshared:102>]]);
recipes.addShaped("power_armor_mk2_chestplate", <techguns:t4_power_chestplate>, [[<techguns:itemshared:102>, <buildcraftsilicon:redstone_chipset:4>, <techguns:itemshared:102>], [<techguns:itemshared:67>, <techguns:t3_power_chestplate>, <techguns:itemshared:67>], [<techguns:itemshared:102>, <ore:plateTitanium>, <techguns:itemshared:102>]]);
recipes.addShaped("power_armor_mk2_helmet", <techguns:t4_power_helmet>, [[<techguns:itemshared:102>, <ore:plateTitanium>, <techguns:itemshared:102>], [<techguns:itemshared:67>, <techguns:t3_power_helmet>, <techguns:itemshared:67>], [<techguns:itemshared:102>, <ore:plateTitanium>, <techguns:itemshared:102>]]);




