#priority 5
// File created by Nykrdaudr
//Crafting table recipes
//TECHGUNS


//============================================================================================================================================================================================
recipes.addShaped("uv_emitter_0", <techguns:itemshared:105>, [[<techguns:itemshared:66>, <techguns:itemshared:63>, <techguns:itemshared:66>], [<techguns:itemshared:53>, <minecraft:redstone_lamp>, <techguns:itemshared:53>], [<techguns:itemshared:53>, <netherex:amethyst_block>, <techguns:itemshared:53>]]);
recipes.addShaped("heavy_cloth", <techguns:itemshared:60>, [[null, <ore:wool>, null], [<ore:wool>, <minecraft:leather>, <ore:wool>], [null, <ore:wool>, null]]);
recipes.addShaped("machine_stack_upgrade", <techguns:itemshared:94>, [[<techguns:itemshared:46>, <ore:dyeGreen>, <techguns:itemshared:46>], [<ore:ingotGold>, <ore:chestWood>, <ore:ingotGold>], [<techguns:itemshared:46>, <ore:ingotGold>, <techguns:itemshared:46>]]);
recipes.addShaped("ore_drill_engine", <techguns:oredrill:3> * 2, [[<ore:paneIron>, <ore:paneIron>, <ore:paneIron>], [<ore:paneIron>, <techguns:itemshared:70>, <ore:paneIron>], [<ore:paneIron>, <ore:paneIron>, <ore:paneIron>]]);
recipes.addShaped("ore_drill_scaffold", <techguns:oredrill:1> * 4, [[<ore:paneIron>, <ore:paneIron>, <ore:paneIron>], [<ore:paneIron>, <techguns:itemshared:46>, <ore:paneIron>], [<ore:paneIron>, <ore:paneIron>, <ore:paneIron>]]);
recipes.addShaped("ore_drill_frame", <techguns:oredrill:0> * 4, [[<techguns:itemshared:46>, <ore:paneIron>, <techguns:itemshared:46>], [<ore:paneIron>, <techguns:itemshared:46>, <ore:paneIron>], [<techguns:itemshared:46>, <ore:paneIron>, <techguns:itemshared:46>]]);
//============================================================================================================================================================================================
//BLOCKS
recipes.addShaped("chem_lab", <techguns:basicmachine:2>, [[<ore:ingotIron>, <sevendaystomine:emptyjar>, <ore:ingotIron>], [<sevendaystomine:emptyjar>, <techguns:itemshared:70>, <sevendaystomine:emptyjar>], [<ore:ingotIron>, <ore:dustRedstone>, <ore:ingotIron>]]);
recipes.addShaped("iron_ladder", <techguns:ladder0:8> * 3, [[<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>], [<ore:nuggetIron>, null, <ore:nuggetIron>]]);
recipes.addShaped("quartz_ladder", <techguns:ladder0:9> * 3, [[<techguns:itemshared:103>, null, <techguns:itemshared:103>], [<techguns:itemshared:103>, <techguns:itemshared:103>, <techguns:itemshared:103>], [<techguns:itemshared:103>, null, <techguns:itemshared:103>]]);
recipes.addShaped("steel_ladder", <techguns:ladder0:11> * 3, [[<ore:nuggetSteel>, null, <ore:nuggetSteel>], [<ore:nuggetSteel>, <ore:nuggetSteel>, <ore:nuggetSteel>], [<ore:nuggetSteel>, null, <ore:nuggetSteel>]]);
recipes.addShaped("slime_ladder", <techguns:slimyladder:3> * 3, [[<minecraft:slime_ball>], [<minecraft:slime_ball>], [<minecraft:slime_ball>]]);
recipes.addShaped("neon_lights", <techguns:neonlights:0>,  [[<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>], [<ore:paneGlass>, <minecraft:glowstone_dust>, <ore:paneGlass>], [<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>]]);
recipes.addShaped("lamps", <techguns:lamp0:0> * 3, [[<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>], [<ore:paneGlass>, <quark:lit_lamp>, <ore:paneGlass>], [<ore:paneGlass>, <ore:paneGlass>, <ore:paneGlass>]]);
recipes.addShaped("lantern", <techguns:lamp0:12> * 3, [[<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>], [<ore:paneGlass>, <quark:lit_lamp>, <ore:paneGlass>], [<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>]]);
recipes.addShaped("door_3x3", <techguns:item_door3x3:0>, [[<techguns:itemshared:50>, <techguns:itemshared:70>, <techguns:itemshared:50>], [<minecraft:piston>, <techguns:itemshared:50>, <minecraft:piston>], [<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:50>]]);
recipes.addShaped("door_up", <techguns:item_door3x3:1>, [[<minecraft:piston>, <techguns:itemshared:70>, <minecraft:piston>], [<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:50>], [<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:50>]]);
recipes.addShaped("door_down", <techguns:item_door3x3:2>, [[<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:50>], [<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:50>], [<minecraft:piston>, <techguns:itemshared:70>, <minecraft:piston>]]);
recipes.addShaped("nether_door", <techguns:item_door3x3:3> * 3, [[<techguns:itemshared:76>, <ore:nether_metal>, <techguns:itemshared:76>], [<techguns:itemshared:70>, <ore:nether_metal>, <techguns:itemshared:70>], [<techguns:itemshared:76>, <ore:nether_metal>, <techguns:itemshared:76>]]);
recipes.addShaped("bunker_door", <techguns:item_bunkerdoor>, [[<techguns:itemshared:46>, <techguns:itemshared:46>], [<techguns:itemshared:46>, <techguns:itemshared:46>], [<techguns:itemshared:46>, <techguns:itemshared:46>]]);
recipes.addShaped("camonet_roof", <techguns:camonet_top> * 6, [[<minecraft:stick>, <ore:treeLeaves>, <minecraft:stick>], [<pvj:mud>, <minecraft:string>, <pvj:mud>], [<minecraft:stick>, <ore:treeLeaves>, <minecraft:stick>]]);
recipes.addShaped("camonet_wall", <techguns:camonet> * 6, [[<minecraft:stick>, <ore:treeLeaves>, <minecraft:stick>], [<minecraft:stick>, <pvj:mud>, <minecraft:stick>]]);
recipes.addShaped("blast_furnace_1", <techguns:simplemachine:11>, [[<techguns:itemshared:46>, <ore:dustRedstone>, <techguns:itemshared:46>], [<techguns:itemshared:46>, <minecraft:furnace>, <techguns:itemshared:46>], [<ore:stone_brick>, <ore:blockIron>, <ore:stone_brick>]]);
recipes.addShaped("upgrade_bench", <techguns:simplemachine2:9>, [[null, <minecraft:crafting_table>, null], [<techguns:itemshared:51>, <ore:gemEmerald>, <techguns:itemshared:51>], [<minecraft:obsidian>, <techguns:itemshared:51>, <minecraft:obsidian>]]);
//============================================================================================================================================================================================
//FROM MODS
recipes.addShaped("worn_ladder", <techguns:ladder0:10> * 3, [[<sevendaystomine:scrapiron>, null, <sevendaystomine:scrapiron>], [<sevendaystomine:scrapiron>, <sevendaystomine:scrapiron>, <sevendaystomine:scrapiron>], [<sevendaystomine:scrapiron>, null, <sevendaystomine:scrapiron>]]);
recipes.addShaped("blast_furnace_0", <techguns:simplemachine:11>, [[<techguns:itemshared:46>, <ore:dustRedstone>, <techguns:itemshared:46>], [<techguns:itemshared:46>, <sevendaystomine:forge>, <techguns:itemshared:46>], [<ore:stone_brick>, <ore:blockIron>, <ore:stone_brick>]]);
recipes.addShaped("heatray_focus", <techguns:itemshared:104>, [[<techguns:itemshared:66>, <techguns:itemshared:63>, <techguns:itemshared:66>], [<techguns:itemshared:50>, <quark:lit_lamp>, <techguns:itemshared:50>], [<techguns:itemshared:50>, <quark:lit_lamp>, <techguns:itemshared:50>]]);
recipes.addShaped("uv_emitter_1", <techguns:itemshared:105>, [[<techguns:itemshared:66>, <techguns:itemshared:63>, <techguns:itemshared:66>], [<techguns:itemshared:53>, <quark:lit_lamp>, <techguns:itemshared:53>], [<techguns:itemshared:53>, <netherex:amethyst_block>, <techguns:itemshared:53>]]);
recipes.addShapeless("gas_can_to_fuel", <techguns:itemshared:27>, [<sevendaystomine:gas_canister>]);
recipes.addShapeless("hdd_to_cybernetics", <techguns:itemshared:69> * 3, [<sevendaystomine:hdd>]);
recipes.addShapeless("cpu_to_cybernetics", <techguns:itemshared:69>, [<sevendaystomine:cpu>]);
recipes.addShaped("circuit_from_7dtm", <techguns:itemshared:65>, [[<sevendaystomine:circuit>, <ore:wireCopper>]]);
recipes.addShaped("circuit_from_7dtm_2", <techguns:itemshared:65>, [[<sevendaystomine:circuit>, <sevendaystomine:wire>]]);
recipes.addShaped("reaction_chamber_glass", <techguns:multiblockmachine:4> * 6, [[<techguns:multiblockmachine:3>, <quark:framed_glass>, <techguns:multiblockmachine:3>], [<techguns:multiblockmachine:3>, <quark:framed_glass>, <techguns:multiblockmachine:3>], [<techguns:multiblockmachine:3>, <quark:framed_glass>]]);
recipes.addShaped("reaction_chamber_controller" <techguns:multiblockmachine:5> [[null, <netherex:soul_glass>, null], [<techguns:itemshared:66>, <techguns:multiblockmachine:3>, <techguns:itemshared:66>], [null, <netherex:soul_glass>, null]]);
//============================================================================================================================================================================================
//ARMOR, WEAPONS AND AMMO
recipes.addShaped("frag_grenade", <techguns:fraggrenade> * 6, [[null, <ore:ingotSteel>, <minecraft:flint_and_steel>], [<ore:ingotSteel>, <minecraft:tnt>, <ore:ingotSteel>], [null, <ore:ingotSteel>, null]]);
recipes.addShaped("mining_charge", <techguns:explosive_charge> * 4, [[<techguns:itemshared:56>, <minecraft:tnt>, <techguns:itemshared:56>], [<minecraft:tnt>, <techguns:itemshared:65>, <minecraft:tnt>], [<techguns:itemshared:56>, <minecraft:tnt>, <techguns:itemshared:56>]]);
recipes.addShaped("power_armor_helmet", <techguns:t3_power_helmet>, [[<techguns:itemshared:66>, <techguns:itemshared:67>, <techguns:itemshared:66>], [<techguns:itemshared:67>, <ore:paneGlassColorless>, <techguns:itemshared:67>]]);
recipes.addShaped("hev_helmet", <techguns:t3_miner_helmet>, [[<techguns:itemshared:53>, <techguns:itemshared:66>, <techguns:itemshared:53>], [<techguns:itemshared:54>, <ore:paneGlassColorless>, <techguns:itemshared:54>]]);
recipes.addShaped("commando_helmet", <techguns:t2_commando_helmet>, [[<ore:ingotObsidianSteel>, <techguns:itemshared:56>, <ore:ingotObsidianSteel>], [<techguns:itemshared:56>, <ore:paneGlassColorless>, <techguns:itemshared:56>]]);
recipes.addShaped("vector_0", <techguns:vector>.withTag({ammo: 25 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:39>, <techguns:itemshared:35>, <techguns:itemshared:43>], [null, <techguns:itemshared:9>, null]]);
recipes.addShaped("vector_1", <techguns:vector>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:39>, <techguns:itemshared:35>, <techguns:itemshared:43>], [null, <techguns:itemshared:10>, null]]);
recipes.addShaped("m4_0", <techguns:m4>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:39>, <techguns:itemshared:34>, <techguns:itemshared:43>], [<ore:nuggetIron>, <techguns:itemshared:13>, <ore:ingotIron>]]);
recipes.addShaped("m4_1", <techguns:m4>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:39>, <techguns:itemshared:34>, <techguns:itemshared:43>], [<ore:nuggetIron>, <techguns:itemshared:14>, <ore:ingotIron>]]);
recipes.addShaped("lmg__0", <techguns:lmg>.withTag({ammo: 100 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:39>, <techguns:itemshared:35>, <techguns:itemshared:43>], [null, <techguns:itemshared:15>, null]]);
recipes.addShaped("lmg_1", <techguns:lmg>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[null, <ore:paneGlassColorless>, <ore:dustRedstone>], [<techguns:itemshared:39>, <techguns:itemshared:35>, <techguns:itemshared:43>], [null, <techguns:itemshared:16>, null]]);
recipes.addShaped("aug_0", <techguns:aug>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:paneGlassColorless>, <techguns:itemshared:50>, <ore:paneGlassColorless>], [<techguns:itemshared:39>, <techguns:itemshared:34>, <techguns:itemshared:43>], [<techguns:itemshared:55>, null, <techguns:itemshared:13>]]);
recipes.addShaped("aug_1", <techguns:aug>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:paneGlassColorless>, <techguns:itemshared:50>, <ore:paneGlassColorless>], [<techguns:itemshared:39>, <techguns:itemshared:34>, <techguns:itemshared:43>], [<techguns:itemshared:55>, null, <techguns:itemshared:14>]]);
recipes.addShaped("m4_alt_0", <techguns:m4_infiltrator>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:blockGlassColorless>, <techguns:itemshared:50>, <ore:blockGlassColorless>], [<ore:blockWool>, <ore:blockWool>, <techguns:aug>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte})], [<ore:dustRedstone>, <ore:dustRedstone>, <ore:ingotSteel>]]);
recipes.addShaped("m4_alt_1", <techguns:m4_infiltrator>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}), [[<ore:blockGlassColorless>, <techguns:itemshared:50>, <ore:blockGlassColorless>], [<ore:blockWool>, <ore:blockWool>, <techguns:aug>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte})], [<ore:dustRedstone>, <ore:dustRedstone>, <ore:ingotSteel>]]);
recipes.addShaped("riot_shield", <techguns:riot_shield>, [[<ore:ingotSteel>, <ore:paneGlassColorless>, <ore:ingotSteel>], [<ore:ingotSteel>, <minecraft:shield>, <ore:ingotSteel>], [<ore:ingotSteel>, <ore:paneGlassColorless>, <ore:ingotSteel>]]);
recipes.addShaped("ballistic_shield", <techguns:ballistic_shield>, [[<techguns:itemshared:51>, <ore:paneGlassColorless>, <techguns:itemshared:51>], [<techguns:itemshared:51>, <minecraft:shield>, <techguns:itemshared:51>], [<techguns:itemshared:51>, <techguns:itemshared:51>, <techguns:itemshared:51>]]);
recipes.addShaped("advanced_shield", <techguns:advanced_shield>, [[<techguns:itemshared:53>, <ore:paneGlassColorless>, <techguns:itemshared:53>], [<techguns:itemshared:53>, <minecraft:shield>, <techguns:itemshared:53>], [<techguns:itemshared:53>, <techguns:itemshared:53>, <techguns:itemshared:53>]]);
recipes.addShaped("gas_mask_0", <techguns:gasmask>, [[<ore:paneGlassColorless>, <techguns:itemshared:56>, <ore:paneGlassColorless>], [<techguns:itemshared:56>, <techguns:itemshared:56>, <techguns:itemshared:56>], [<techguns:itemshared:56>, <techguns:itemshared:89>, <techguns:itemshared:56>]]);
recipes.addShaped("gas_mask_1", <techguns:gasmask>, [[<ore:paneGlassLightGray>, <techguns:itemshared:56>, <ore:paneGlassLightGray>], [<techguns:itemshared:56>, <techguns:itemshared:56>, <techguns:itemshared:56>], [<techguns:itemshared:56>, <techguns:itemshared:89>, <techguns:itemshared:56>]]);
recipes.addShaped("nether_combat_boots", <techguns:t4_praetor_boots>, [[null, <techguns:itemshared:70>, null], [<techguns:itemshared:67>, null, <techguns:itemshared:67>], [<ore:plateObsidianSteel>, null, <ore:plateObsidianSteel>]]);
recipes.addShaped("nether_combat_leggings", <techguns:t4_praetor_leggings>, [[<techguns:itemshared:67>, <techguns:itemshared:67>, <techguns:itemshared:67>], [<ore:circuitElite>, null, <ore:circuitElite>], [<ore:plateObsidianSteel>, null, <ore:plateObsidianSteel>]]);
recipes.addShaped("nether_combat_chestplate", <techguns:t4_praetor_chestplate>, [[<techguns:itemshared:70>, <buildcraftfactory:heat_exchange>, <techguns:itemshared:70>], [<techguns:itemshared:67>, <techguns:itemshared:66>, <techguns:itemshared:67>], [<ore:plateObsidianSteel>, <techguns:itemshared:67>, <ore:plateObsidianSteel>]]);
recipes.addShaped("nether_combat_helmet", <techguns:t4_praetor_helmet>, [[<ore:plateObsidianSteel>, <buildcraftfactory:heat_exchange>, <ore:plateObsidianSteel>], [<techguns:itemshared:67>, <ore:circuitElite>, <techguns:itemshared:67>], [<ore:plateObsidianSteel>, <ore:paneGlassColorless>, <ore:plateObsidianSteel>]]);
recipes.addShaped("power_armor_mk2_boots", <techguns:t4_power_boots>, [[<techguns:itemshared:67>, <techguns:itemshared:59>, <techguns:itemshared:67>], [<techguns:itemshared:102>, <techguns:t3_power_boots>, <techguns:itemshared:102>], [<techguns:itemshared:67>, <ore:plateTitanium>, <techguns:itemshared:67>]]);
recipes.addShaped("power_armor_mk2_leggings", <techguns:t4_power_leggings>, [[<techguns:itemshared:67>, <ore:plateTitanium>, <techguns:itemshared:67>], [<techguns:itemshared:59>, <techguns:t3_power_leggings>, <techguns:itemshared:59>], [<techguns:itemshared:102>, <buildcraftsilicon:redstone_chipset:4>, <techguns:itemshared:102>]]);
recipes.addShaped("power_armor_mk2_chestplate", <techguns:t4_power_chestplate>, [[<techguns:itemshared:102>, <buildcraftsilicon:redstone_chipset:4>, <techguns:itemshared:102>], [<techguns:itemshared:67>, <techguns:t3_power_chestplate>, <techguns:itemshared:67>], [<techguns:itemshared:102>, <ore:plateTitanium>, <techguns:itemshared:102>]]);
recipes.addShaped("power_armor_mk2_helmet", <techguns:t4_power_helmet>, [[<techguns:itemshared:102>, <ore:plateTitanium>, <techguns:itemshared:102>], [<techguns:itemshared:67>, <techguns:t3_power_helmet>, <techguns:itemshared:67>], [<techguns:itemshared:102>, <ore:plateTitanium>, <techguns:itemshared:102>]]);
recipes.addShaped("stick_granates", <techguns:stielgranate> * 16, [[null, <ore:ingotIron>, <minecraft:tnt>], [null, <sevendaystomine:woodplank>, <ore:ingotIron>], [<ore:ingotIron>, null, null]]);
recipes.addShaped("stone_bullets", <techguns:itemshared:0> * 8, [[<sevendaystomine:smallstone>, <sevendaystomine:smallstone>, <sevendaystomine:smallstone>], [<sevendaystomine:smallstone>, <minecraft:gunpowder>, <sevendaystomine:smallstone>], [<sevendaystomine:smallstone>, <sevendaystomine:smallstone>, <sevendaystomine:smallstone>]]);
recipes.addShaped("pistol_rounds", <techguns:itemshared:1> * 3, [[<ore:nuggetCopper>, <ore:ingotLead>, <ore:nuggetCopper>], [<ore:nuggetCopper>, <minecraft:gunpowder>, <ore:nuggetCopper>], [<ore:nuggetCopper>, <ore:nuggetCopper>, <ore:nuggetCopper>]]);
recipes.addShaped("shotgun_bullets", <techguns:itemshared:2> * 3, [[<ore:nuggetLead>, <ore:nuggetLead>, <ore:nuggetLead>],  [<ore:nuggetCopper>, <minecraft:gunpowder>, <ore:nuggetCopper>], [<ore:nuggetCopper>, <ore:nuggetCopper>, <ore:nuggetCopper>]]);
recipes.addShaped("rocket", <techguns:itemshared:7>, [[null, <ore:nuggetIron>, null], [<techguns:itemshared:46>, <minecraft:tnt>, <techguns:itemshared:46>], [<techguns:itemshared:46>, <minecraft:gunpowder>, <techguns:itemshared:46>]]);
recipes.addShaped("smg_magazine1", <techguns:itemshared:9>, [[<techguns:itemshared:10>, <techguns:itemshared:1>], [<techguns:itemshared:1>, <techguns:itemshared:1>]]);
recipes.addShaped("smg_magazine2", <techguns:itemshared:10>, [[<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:nuggetIron>, <techguns:itemshared:57>, <ore:nuggetIron>]]);
recipes.addShaped("pistol_magazine", <techguns:itemshared:12>, [[<ore:nuggetIron>, null, <ore:nuggetIron>], [<ore:nuggetIron>, <techguns:itemshared:57>, <ore:nuggetIron>], [<ore:nuggetIron>, <ore:ingotIron>, <ore:nuggetIron>]]);
recipes.addShaped("assault_magazine", <techguns:itemshared:14>, [[<ore:nuggetSteel>, null, <ore:nuggetSteel>], [<ore:nuggetSteel>, null, <ore:nuggetSteel>], [<ore:nuggetSteel>, <techguns:itemshared:57>, <ore:nuggetSteel>]]);
recipes.addShapedMirrored("lmg_magazine", <techguns:itemshared:16> * 2, [[null, <ore:ingotSteel>, <ore:ingotSteel>], [<ore:ingotSteel>, <techguns:itemshared:57>, <ore:ingotSteel>], [<ore:ingotSteel>, <ore:ingotSteel>, <ore:ingotSteel>]]);
recipes.addShaped("minigun_drum", <techguns:itemshared:18> * 2, [[<ore:ingotSteel>, <ore:ingotSteel>, <ore:ingotSteel>], [<techguns:itemshared:55>, <techguns:itemshared:58>, <techguns:itemshared:55>], [<ore:ingotSteel>, <ore:ingotSteel>, <ore:ingotSteel>]]);
recipes.addShaped("as50_magazine", <techguns:itemshared:20> * 2, [[<ore:ingotSteel>, null, <ore:ingotSteel>], [<ore:ingotSteel>, null, <ore:ingotSteel>], [<ore:ingotSteel>, <techguns:itemshared:57>, <ore:ingotSteel>]]);
recipes.addShaped("advanced_magazine", <techguns:itemshared:22> * 2, [[<ore:ingotObsidianSteel>, null, <ore:ingotObsidianSteel>], [<ore:ingotObsidianSteel>, null, <ore:ingotObsidianSteel>], [<ore:ingotObsidianSteel>, <techguns:itemshared:58>, <ore:ingotObsidianSteel>]]);
recipes.addShaped("empty_tank1", <techguns:itemshared:24> * 2, [[<techguns:itemshared:48>, <minecraft:lever>, <techguns:itemshared:48>], [<techguns:itemshared:48>, null, <techguns:itemshared:48>], [<techguns:itemshared:48>, <techguns:itemshared:48>, <techguns:itemshared:48>]]);
recipes.addShaped("empty_tank2", <techguns:itemshared:24> * 2, [[<techguns:itemshared:46>, <minecraft:lever>, <techguns:itemshared:46>], [<techguns:itemshared:46>, null, <techguns:itemshared:46>], [<techguns:itemshared:46>, <techguns:itemshared:46>, <techguns:itemshared:46>]]);
recipes.addShaped("fuel", <techguns:itemshared:28>  * 2, [[<techguns:itemshared:55>], [<ore:blockGlass>], [<techguns:itemshared:55>]]);
recipes.addShaped("smg_fire_magazine", <techguns:itemshared:112>, [[<techguns:itemshared:10>, <techguns:itemshared:109>], [<techguns:itemshared:109>, <techguns:itemshared:109>]]);
recipes.addShaped("nuke", <techguns:itemshared:118>, [[<techguns:itemshared:52>, <techguns:itemshared:65>, <techguns:itemshared:52>], [<techguns:itemshared:75>, <ore:ingotUraniumEnriched>, <techguns:itemshared:75>], [<techguns:itemshared:52>, <techguns:itemshared:65>, <techguns:itemshared:52>]]);
recipes.addShaped("redstone_battery", <techguns:itemshared:125>, [[<ore:nuggetCopper>, <techguns:itemshared:56>, <ore:nuggetCopper>], [<techguns:itemshared:47>, <ore:dustRedstone>, <techguns:itemshared:47>], [<techguns:itemshared:47>, <buildcraftsilicon:redstone_chipset:0>, <techguns:itemshared:47>]]);
recipes.addShaped("stone_barrel", <techguns:itemshared:37>, [[<minecraft:stone_slab:0>, <minecraft:stone_slab:0>, <minecraft:stone_slab:0>], [null, null, null], [<minecraft:stone_slab:0>, <minecraft:stone_slab:0>, <minecraft:stone_slab:0>]]);
