#priority 5
// File created by Nykrdaudr
//Crafting table recipes
//TRAVELERS BACKPACK


//============================================================================================================================================================================================
recipes.addShaped("backpack_tank", <travelersbackpack:backpack_tank>, [[<ore:blockGlassColorless>, <ore:ingotIron>, <ore:blockGlassColorless>], [<ore:blockGlassColorless>, <ore:blockGlassColorless>, <ore:blockGlassColorless>], [<ore:blockGlassColorless>, <ore:ingotIron>, <ore:blockGlassColorless>]]);
// recipes.addShaped("backpack_hose", <travelersbackpack:hose>, [[
recipes.addShapeless("backpack_basic_0", <travelersbackpack:travelers_backpack:0>, [<travelersbackpack:travelers_backpack:*>]);
recipes.addShaped("backpack_basic_1", <travelersbackpack:travelers_backpack:0>, [[<ore:leather>, <quark:gold_button>, <ore:leather>], [<travelersbackpack:backpack_tank>, <ore:chestWood>, <travelersbackpack:backpack_tank>], [<ore:leather>, <ore:sleepingBag>, <ore:leather>]]);
recipes.addShaped("backpack_white", <travelersbackpack:travelers_backpack:72>, [[<ore:woolWhite>, <ore:woolWhite>, <ore:woolWhite>], [<ore:woolWhite>, <travelersbackpack:travelers_backpack:*>, <ore:woolWhite>], [<ore:woolWhite>, <ore:woolWhite>, <ore:woolWhite>]]);
recipes.addShaped("backpack_orange", <travelersbackpack:travelers_backpack:49>, [[<ore:woolOrange>, <ore:woolOrange>, <ore:woolOrange>], [<ore:woolOrange>, <travelersbackpack:travelers_backpack:*>, <ore:woolOrange>], [<ore:woolOrange>, <ore:woolOrange>, <ore:woolOrange>]]);
recipes.addShaped("backpack_magenta", <travelersbackpack:travelers_backpack:40>, [[<ore:woolMagenta>, <ore:woolMagenta>, <ore:woolMagenta>], [<ore:woolMagenta>, <travelersbackpack:travelers_backpack:*>, <ore:woolMagenta>], [<ore:woolMagenta>, <ore:woolMagenta>, <ore:woolMagenta>]]);
recipes.addShaped("backpack_lightBlue", <travelersbackpack:travelers_backpack:36>, [[<ore:woolLightBlue>, <ore:woolLightBlue>, <ore:woolLightBlue>], [<ore:woolLightBlue>, <travelersbackpack:travelers_backpack:*>, <ore:woolLightBlue>], [<ore:woolLightBlue>, <ore:woolLightBlue>, <ore:woolLightBlue>]]);
recipes.addShaped("backpack_yellow", <travelersbackpack:travelers_backpack:74>, [[<ore:woolYellow>, <ore:woolYellow>, <ore:woolYellow>], [<ore:woolYellow>, <travelersbackpack:travelers_backpack:*>, <ore:woolYellow>], [<ore:woolYellow>, <ore:woolYellow>, <ore:woolYellow>]]);
recipes.addShaped("backpack_lime", <travelersbackpack:travelers_backpack:39>, [[<ore:woolLime>, <ore:woolLime>, <ore:woolLime>], [<ore:woolLime>, <travelersbackpack:travelers_backpack:*>, <ore:woolLime>], [<ore:woolLime>, <ore:woolLime>, <ore:woolLime>]]);
recipes.addShaped("backpack_pink", <travelersbackpack:travelers_backpack:52>, [[<ore:woolPink>, <ore:woolPink>, <ore:woolPink>], [<ore:woolPink>, <travelersbackpack:travelers_backpack:*>, <ore:woolPink>], [<ore:woolPink>, <ore:woolPink>, <ore:woolPink>]]);
recipes.addShaped("backpack_gray", <travelersbackpack:travelers_backpack:31>, [[<ore:woolGray>, <ore:woolGray>, <ore:woolGray>], [<ore:woolGray>, <travelersbackpack:travelers_backpack:*>, <ore:woolGray>], [<ore:woolGray>, <ore:woolGray>, <ore:woolGray>]]);
recipes.addShaped("backpack_lightGray", <travelersbackpack:travelers_backpack:38>, [[<ore:woolLightGray>, <ore:woolLightGray>, <ore:woolLightGray>], [<ore:woolLightGray>, <travelersbackpack:travelers_backpack:*>, <ore:woolLightGray>], [<ore:woolLightGray>, <ore:woolLightGray>, <ore:woolLightGray>]]);
recipes.addShaped("backpack_cyan", <travelersbackpack:travelers_backpack:21>, [[<ore:woolCyan>, <ore:woolCyan>, <ore:woolCyan>], [<ore:woolCyan>, <travelersbackpack:travelers_backpack:*>, <ore:woolCyan>], [<ore:woolCyan>, <ore:woolCyan>, <ore:woolCyan>]]);
recipes.addShaped("backpack_purple", <travelersbackpack:travelers_backpack:55>, [[<ore:woolPurple>, <ore:woolPurple>, <ore:woolPurple>], [<ore:woolPurple>, <travelersbackpack:travelers_backpack:*>, <ore:woolPurple>], [<ore:woolPurple>, <ore:woolPurple>, <ore:woolPurple>]]);
recipes.addShaped("backpack_blue", <travelersbackpack:travelers_backpack:14>, [[<ore:woolBlue>, <ore:woolBlue>, <ore:woolBlue>], [<ore:woolBlue>, <travelersbackpack:travelers_backpack:*>, <ore:woolBlue>], [<ore:woolBlue>, <ore:woolBlue>, <ore:woolBlue>]]);
recipes.addShaped("backpack_brown", <travelersbackpack:travelers_backpack:16>, [[<ore:woolBrown>, <ore:woolBrown>, <ore:woolBrown>], [<ore:woolBrown>, <travelersbackpack:travelers_backpack:*>, <ore:woolBrown>], [<ore:woolBrown>, <ore:woolBrown>, <ore:woolBrown>]]);
recipes.addShaped("backpack_green", <travelersbackpack:travelers_backpack:32>, [[<ore:woolGreen>, <ore:woolGreen>, <ore:woolGreen>], [<ore:woolGreen>, <travelersbackpack:travelers_backpack:*>, <ore:woolGreen>], [<ore:woolGreen>, <ore:woolGreen>, <ore:woolGreen>]]);
recipes.addShaped("backpack_red", <travelersbackpack:travelers_backpack:58>, [[<ore:woolRed>, <ore:woolRed>, <ore:woolRed>], [<ore:woolRed>, <travelersbackpack:travelers_backpack:*>, <ore:woolRed>], [<ore:woolRed>, <ore:woolRed>, <ore:woolRed>]]);
recipes.addShaped("backpack_black", <travelersbackpack:travelers_backpack:3>, [[<ore:woolBlack>, <ore:woolBlack>, <ore:woolBlack>], [<ore:woolBlack>, <travelersbackpack:travelers_backpack:*>, <ore:woolBlack>], [<ore:woolBlack>, <ore:woolBlack>, <ore:woolBlack>]]);
recipes.addShaped("backpack_sandstone", <travelersbackpack:travelers_backpack:59>, [[<ore:yellow_sandstone_cobble>, <ore:yellow_sandstone_cobble>, <ore:yellow_sandstone_cobble>], [<ore:yellow_sandstone_cobble>, <travelersbackpack:travelers_backpack:*>, <ore:yellow_sandstone_cobble>], [<ore:yellow_sandstone_cobble>, <ore:yellow_sandstone_cobble>, <ore:yellow_sandstone_cobble>]]);
recipes.addShaped("backpack_wolf", <travelersbackpack:travelers_backpack:73>, [[<minecraft:bone>, <ore:woolWhite>, <minecraft:bone>], [<ore:woolWhite>, <travelersbackpack:travelers_backpack:*>, <ore:woolWhite>], [<minecraft:bone>, <ore:woolWhite>, <minecraft:bone>]]);
recipes.addShaped("backpack_sheep", <travelersbackpack:travelers_backpack:60>, [[<ore:woolWhite>, <ore:woolPink>, <ore:woolWhite>], [<ore:woolWhite>, <travelersbackpack:travelers_backpack:*>, <ore:woolWhite>], [<ore:woolWhite>, <ore:woolWhite>, <ore:woolWhite>,]]);
recipes.addShaped("backpack_overworld", <travelersbackpack:travelers_backpack:50>, [[<ore:woolLightBlue>, <chisel:cloud:*>, <ore:woolLightBlue>], [<minecraft:grass>, <travelersbackpack:travelers_backpack:*>, <minecraft:grass>], [<ore:stonesCobble>, <ore:stonesCobble>, <ore:stonesCobble>]]);
recipes.addShaped("backpack_ocelot", <travelersbackpack:travelers_backpack:29>, [[<minecraft:fish:*>, <ore:woolYellow>, <minecraft:fish:*>], [<ore:woolYellow>, <travelersbackpack:travelers_backpack:*>, <ore:woolYellow>], [<minecraft:fish:*>, <ore:woolYellow>, <minecraft:fish:*>]]);
recipes.addShaped("backpack_silverfish", <travelersbackpack:travelers_backpack:61>, [[<ore:cracked_stone_brick>, <ore:woolLightGray>, <ore:cracked_stone_brick>], [<ore:cracked_stone_brick>, <travelersbackpack:travelers_backpack:*>, <ore:cracked_stone_brick>], [<ore:cracked_stone_brick>, <ore:woolLightGray>, <ore:cracked_stone_brick>]]);
recipes.addShaped("backpack_squid", <travelersbackpack:travelers_backpack:62>, [[<ore:woolBlue>, <ore:ink>, <ore:woolBlue>], [<ore:ink>, <travelersbackpack:travelers_backpack:*>, <ore:ink>], [<ore:woolBlue>, <ore:ink>, <ore:woolBlue>]]);
recipes.addShaped("backpack_enderman", <travelersbackpack:travelers_backpack:26>, [[<minecraft:ender_pearl>, <quark:biotite_block>, <minecraft:ender_pearl>], [<quark:biotite_block>, <travelersbackpack:travelers_backpack:*>, <quark:biotite_block>], [<minecraft:ender_pearl>, <quark:biotite_block>, <minecraft:ender_pearl>]]);
recipes.addShaped("backpack_gold", <travelersbackpack:travelers_backpack:9>, [[<minecraft:gold_nugget>, <ore:blockGold>, <minecraft:gold_nugget>], [<ore:blockGold>, <travelersbackpack:travelers_backpack:*>, <ore:blockGold>], [<ore:ingotGold>, <ore:blockGold>, <ore:ingotGold>]]);
recipes.addShaped("backpack_iron", <travelersbackpack:travelers_backpack:10>, [[<minecraft:iron_nugget>, <ore:blockIron>, <minecraft:iron_nugget>], [<ore:blockIron>, <travelersbackpack:travelers_backpack:*>, <ore:blockIron>], [<ore:ingotIron>, <ore:blockIron>, <ore:ingotIron>]]);
recipes.addShaped("backpack_bookshelf", <travelersbackpack:travelers_backpack:15>, [[<ore:bookshelf>, null, <ore:bookshelf>], [<ore:bookshelf>, <travelersbackpack:travelers_backpack:*>, <ore:bookshelf>], [<ore:book>, <ore:book>, <ore:book>]]);
recipes.addShaped("backpack_diamond", <travelersbackpack:travelers_backpack:7>, [[<ore:gemDiamond>, <ore:blockDiamond>, <ore:gemDiamond>], [<ore:blockDiamond>, <travelersbackpack:travelers_backpack:*>, <ore:blockDiamond>], [<ore:gemDiamond>, <ore:blockDiamond>, <ore:gemDiamond>]]);
recipes.addShaped("backpack_snow", <travelersbackpack:travelers_backpack:68>, [[<ore:iceSoft>, <ore:iceSoft>, <ore:iceSoft>], [<minecraft:snow>, <travelersbackpack:travelers_backpack:*>, <minecraft:snow>], [<minecraft:snowball>, <minecraft:snow>, <minecraft:snowball>]]);
recipes.addShaped("backpack_glowstone", <travelersbackpack:travelers_backpack:37>, [[<ore:dustGlowstone>, <ore:glowstone>, <ore:dustGlowstone>], [<ore:glowstone>, <travelersbackpack:travelers_backpack:*>, <ore:glowstone>], [<ore:dustGlowstone>, <ore:glowstone>, <ore:dustGlowstone>]]);
recipes.addShaped("backpack_mooshroom", <travelersbackpack:travelers_backpack:45>, [[<minecraft:mushroom_stew>, <ore:shroomRed>, <minecraft:mycelium>], [<ore:shroomBrown>, <travelersbackpack:travelers_backpack:*>, <ore:shroomBrown>], [<minecraft:mycelium>, <ore:shroomRed>, <minecraft:mushroom_stew>]]);
recipes.addShaped("backpack_nether", <travelersbackpack:travelers_backpack:46>, [[<ore:gemQuartz>, <minecraft:nether_wart>, <ore:gemQuartz>], [<ore:netherrack>, <travelersbackpack:travelers_backpack:*>, <ore:netherrack>], [<ore:gemQuartz>, <minecraft:lava_bucket>, <ore:gemQuartz>]]);
recipes.addShaped("backpack_emerald", <travelersbackpack:travelers_backpack:8>, [[<ore:gemEmerald>, <ore:blockEmerald>, <ore:gemEmerald>], [<ore:blockEmerald>, <travelersbackpack:travelers_backpack:*>, <ore:blockEmerald>], [<ore:gemEmerald>, <ore:blockEmerald>, <ore:gemEmerald>]]);
recipes.addShaped("backpack_quartz", <travelersbackpack:travelers_backpack:56>, [[<ore:quartz>, <ore:gemQuartz>, <ore:quartz>], [<ore:gemQuartz>, <travelersbackpack:travelers_backpack:*>, <ore:gemQuartz>], [<ore:quartz>, <ore:gemQuartz>, <ore:quartz>]]);
recipes.addShaped("backpack_carbon", <travelersbackpack:travelers_backpack:6>, [[<minecraft:coal:*>, <ore:blockCarbon>, <minecraft:coal:*>], [<ore:blockCarbon>, <travelersbackpack:travelers_backpack:*>, <ore:blockCarbon>], [<minecraft:coal:*>, <ore:blockCarbon>, <minecraft:coal:*>]]);
recipes.addShaped("backpack_chest", <travelersbackpack:travelers_backpack:19>, [[<ore:chestWood>, <ore:plankWood>, <ore:chestWood>], [<ore:plankWood>, <travelersbackpack:travelers_backpack:*>, <ore:plankWood>], [<ore:chestWood>, <ore:plankWood>, <ore:chestWood>]]);
recipes.addShaped("backpack_redstone", <travelersbackpack:travelers_backpack:13>, [[<ore:dustRedstone>, <ore:blockRedstone>, <ore:dustRedstone>], [<ore:blockRedstone>, <travelersbackpack:travelers_backpack:*>, <ore:blockRedstone>], [<ore:dustRedstone>, <ore:blockRedstone>, <ore:dustRedstone>]]);
recipes.addShaped("backpack_slime", <travelersbackpack:travelers_backpack:67>, [[<minecraft:slime_ball>, <minecraft:slime_ball>, <minecraft:slime_ball>], [<pvj:slime_droplet>, <travelersbackpack:travelers_backpack:*>, <pvj:slime_droplet>], [<minecraft:slime>, <minecraft:slime>, <minecraft:slime>]]);
recipes.addShaped("backpack_lapis", <travelersbackpack:travelers_backpack:12>, [[<ore:gemLapis>, <ore:blockLapis>, <ore:gemLapis>], [<ore:blockLapis>, <travelersbackpack:travelers_backpack:*>, <ore:blockLapis>], [<ore:gemLapis>, <ore:blockLapis>, <ore:gemLapis>]]);
recipes.addShaped("backpack_cow", <travelersbackpack:travelers_backpack:1>, [[<minecraft:beef>, <minecraft:leather>, <minecraft:beef>], [<minecraft:beef>, <travelersbackpack:travelers_backpack:*>, <minecraft:beef>], [<minecraft:leather>, <minecraft:milk_bucket>, <minecraft:leather>]]);
recipes.addShaped("backpack_blaze", <travelersbackpack:travelers_backpack:4>, [[<minecraft:blaze_rod>, <quark:blaze_lantern>, <minecraft:blaze_rod>], [<netherex:blazed_wither_bone>, <travelersbackpack:travelers_backpack:*>, <netherex:blazed_wither_bone>], [<minecraft:blaze_powder>, <forge:bucketfilled>.withTag({FluidName: "bcop-gaseous_lava-searing", Amount: 1000}), <minecraft:fire_charge>]]);
recipes.addShaped("backpack_carrot", <travelersbackpack:travelers_backpack:5>, [[<pvj:short_grass>, <pvj:short_grass>, <pvj:short_grass>], [<minecraft:carrot>, <travelersbackpack:travelers_backpack:*>, <minecraft:carrot>], [<minecraft:carrot>, <minecraft:golden_carrot>, <minecraft:carrot>]]);
recipes.addShaped("backpack_cactus", <travelersbackpack:travelers_backpack:17>, [[<pvj:small_cactus>, <minecraft:dye:2>, <pvj:small_cactus>], [<minecraft:cactus>, <travelersbackpack:travelers_backpack:*>, <minecraft:cactus>], [<ore:sand>, <ore:sand>, <ore:sand>]]);
recipes.addShaped("backpack_cake", <travelersbackpack:travelers_backpack:18>, [[<ore:egg>, <minecraft:cake>, <ore:egg>], [<minecraft:wheat>, <travelersbackpack:travelers_backpack:*>, <minecraft:wheat>], [<minecraft:sugar>, <minecraft:milk_bucket>, <minecraft:sugar>]]);
recipes.addShaped("backpack_cookie", <travelersbackpack:travelers_backpack:20>, [[<minecraft:cookie>, <minecraft:dye:3>, <minecraft:cookie>], [<minecraft:wheat>, <travelersbackpack:travelers_backpack:*>, <minecraft:wheat>], [<minecraft:cookie>, <minecraft:cookie>, <minecraft:cookie>]]);
recipes.addShaped("backpack_dragon", <travelersbackpack:travelers_backpack:22>, [[<openblocks:sky:1>, <minecraft:skull:5>, <openblocks:sky:1>], [<quark:enderdragon_scale>, <travelersbackpack:travelers_backpack:*>, <quark:enderdragon_scale>], [<minecraft:end_stone>, <minecraft:dragon_egg>, <minecraft:end_stone>]]);
recipes.addShaped("backpack_egg", <travelersbackpack:travelers_backpack:23>, [[<ore:egg>, <ore:egg>, <ore:egg>], [<ore:egg>, <travelersbackpack:travelers_backpack:*>, <ore:egg>], [<ore:egg>, <ore:egg>, <ore:egg>]]);
recipes.addShaped("backpack_end", <travelersbackpack:travelers_backpack:27>, [[<minecraft:ender_eye>, <minecraft:end_stone>, <minecraft:ender_eye>], [<minecraft:end_stone>, <travelersbackpack:travelers_backpack:*>, <minecraft:end_stone>], [<minecraft:ender_eye>, <minecraft:end_stone>, <minecraft:ender_eye>]]);
recipes.addShaped("backpack_chicken", <travelersbackpack:travelers_backpack:28>, [[<minecraft:feather>, <minecraft:gold_nugget>, <minecraft:feather>], [<minecraft:chicken>, <travelersbackpack:travelers_backpack:*>, <minecraft:chicken>], [<minecraft:egg>, <sevendaystomine:birdnest>, <minecraft:egg>]]);
recipes.addShaped("backpack_ghast", <travelersbackpack:travelers_backpack:30>, [[<netherex:ghast_meat_raw>, <minecraft:fire_charge>, <netherex:ghast_meat_raw>], [<minecraft:ghast_tear>, <travelersbackpack:travelers_backpack>, <minecraft:ghast_tear>], [<netherex:ghast_meat_raw>, <netherex:ghast_queen_tear>, <netherex:ghast_meat_raw>]]);
recipes.addShaped("backpack_hay_bale", <travelersbackpack:travelers_backpack:33>, [[<quark:thatch_stairs>, <quark:thatch_slab>, <quark:thatch_stairs>], [<quark:thatch>, <travelersbackpack:travelers_backpack:*>, <quark:thatch>], [<minecraft:hay_block>, <minecraft:hay_block>, <minecraft:hay_block>]]);
recipes.addShaped("backpack_horse", <travelersbackpack:travelers_backpack:34>, [[<minecraft:leather>, <quark:horse_whistle>, <minecraft:leather>], [<minecraft:hay_block>, <travelersbackpack:travelers_backpack:*>, <minecraft:hay_block>], [<minecraft:leather>, <minecraft:saddle>, <minecraft:leather>]]);
recipes.addShaped("backpack_leather", <travelersbackpack:travelers_backpack:35>, [[<ore:leather>, <ore:leather>, <ore:leather>], [<ore:leather>, <travelersbackpack:travelers_backpack:*>, <ore:leather>], [<ore:leather>, <ore:leather>, <ore:leather>]]);
recipes.addShaped("backpack_magma_cube", <travelersbackpack:travelers_backpack:41>, [[<netherex:congealed_magma_cream>, <minecraft:magma_cream>, <netherex:congealed_magma_cream>], [<minecraft:magma_cream>, <travelersbackpack:travelers_backpack:*>, <minecraft:magma_cream>], [<minecraft:magma>, <minecraft:lava_bucket>, <minecraft:magma>]]);
recipes.addShaped("backpack_melon", <travelersbackpack:travelers_backpack:42>, [[<minecraft:melon>, <minecraft:melon_seeds>, <minecraft:melon>], [<minecraft:melon>, <travelersbackpack:travelers_backpack:*>, <minecraft:melon>], [<minecraft:melon_block>, <minecraft:speckled_melon>, <minecraft:melon_block>]]);
recipes.addShaped("backpack_brown_mushroom", <travelersbackpack:travelers_backpack:43>, [[<netherex:brown_elder_mushroom>, <minecraft:brown_mushroom>, <netherex:brown_elder_mushroom>], [<minecraft:brown_mushroom>, <travelersbackpack:travelers_backpack:*>, <minecraft:brown_mushroom>], [<netherex:brown_elder_mushroom>, <minecraft:brown_mushroom>, <netherex:brown_elder_mushroom>]]);
recipes.addShaped("backpack_red_mushroom", <travelersbackpack:travelers_backpack:44>, [[<netherex:red_elder_mushroom>, <minecraft:red_mushroom>, <netherex:red_elder_mushroom>], [<minecraft:red_mushroom>, <travelersbackpack:travelers_backpack:*>, <minecraft:red_mushroom>], [<netherex:red_elder_mushroom>, <minecraft:red_mushroom>, <netherex:red_elder_mushroom>]]);
recipes.addShapedMirrored("backpack_wither", <travelersbackpack:travelers_backpack:47>, [[<minecraft:skull:1>, <minecraft:skull:1>, <minecraft:skull:1>], [<minecraft:soul_sand>, <travelersbackpack:travelers_backpack:*>, <minecraft:soul_sand>], [<minecraft:nether_star>, <minecraft:soul_sand>, <ore:gemDiamond>]]);
recipes.addShaped("backpack_obsidian", <travelersbackpack:travelers_backpack:48>, [[<techguns:itemshared:51>, <chisel:obsidian:*>, <techguns:itemshared:51>], [<chisel:obsidian:*>, <travelersbackpack:travelers_backpack:*>, <chisel:obsidian:*>], [<techguns:itemshared:84>, <chisel:obsidian:*>, <techguns:itemshared:84>]]);
recipes.addShaped("backpack_pig", <travelersbackpack:travelers_backpack:53>, [[<quark:tallow>, <minecraft:porkchop>, <quark:tallow>], [<minecraft:porkchop>, <travelersbackpack:travelers_backpack:*>, <minecraft:porkchop>], [<quark:tallow>, <minecraft:porkchop>, <quark:tallow>]]);
recipes.addShaped("backpack_pumpkin", <travelersbackpack:travelers_backpack:54>, [[<minecraft:pumpkin>, <minecraft:pumpkin>, <minecraft:pumpkin>], [<minecraft:pumpkin>, <travelersbackpack:travelers_backpack:*>, <minecraft:pumpkin>], [<minecraft:pumpkin>, <minecraft:pumpkin_seeds>, <minecraft:pumpkin>]]);
recipes.addShaped("backpack_rainbow", <travelersbackpack:travelers_backpack:57>, [[<quark:rune:16>, <quark:rune:16>, <quark:rune:16>], [<quark:rune:16>, <travelersbackpack:travelers_backpack:*>, <quark:rune:16>], [<quark:rune:16>, <quark:rune:16>, <quark:rune:16>]]);
recipes.addShaped("backpack_sunflower", <travelersbackpack:travelers_backpack:63>, [[<minecraft:double_plant:0>, <minecraft:double_plant:0>, <minecraft:double_plant:0>], [<minecraft:double_plant:0>, <travelersbackpack:travelers_backpack:*>, <minecraft:double_plant:0>], [<minecraft:double_plant:0>, <minecraft:double_plant:0>, <minecraft:double_plant:0>]]);
recipes.addShaped("backpack_creeper", <travelersbackpack:travelers_backpack:64>, [[<ore:treeLeaves>, <minecraft:skull:4>, <ore:treeLeaves>], [<spartanweaponry:dynamite>, <travelersbackpack:travelers_backpack:*>, <spartanweaponry:dynamite>], [<ore:treeLeaves>, <forge:bucketfilled>.withTag({FluidName: "creeper_acid", Amount: 1000}), <ore:treeLeaves>]]);
recipes.addShaped("backpack_skeleton", <travelersbackpack:travelers_backpack:65>, [[<pvj:bones>, <minecraft:skull:0>, <pvj:bones>], [<ore:bows>, <travelersbackpack:travelers_backpack:*>, <minecraft:bone>], [<netherex:bone_sliver>, <ore:arrow>, <netherex:bone_sliver>]]);
recipes.addShaped("backpack_wither_skeleton", <travelersbackpack:travelers_backpack:66>, [[<netherex:wither_dust>, <minecraft:skull:1>, <netherex:wither_dust>], [<spartanweaponry:longsword_stone>, <travelersbackpack:travelers_backpack:*>, <netherex:wither_bone>], [<netherex:wither_bone>, <netherex:wither_dust>, <netherex:wither_bone>]]);
recipes.addShaped("backpack_spider", <travelersbackpack:travelers_backpack:69>, [[<minecraft:carpet:15>, <minecraft:wool:15>, <minecraft:carpet:15>], [<minecraft:spider_eye>, <travelersbackpack:travelers_backpack:*>, <minecraft:spider_eye>], [<quark:biome_cobblestone:2>, <minecraft:web>, <quark:biome_cobblestone:2>]]);
recipes.addShaped("backpack_sponge", <travelersbackpack:travelers_backpack:70>, [[<oe:sponge_chunk>, <minecraft:sponge>, <oe:sponge_chunk>], [<oe:tube_sponge>, <travelersbackpack:travelers_backpack:*>, <oe:tube_sponge>], [<minecraft:sponge>, <minecraft:sponge>, <minecraft:sponge>]]);
recipes.addShaped("backpack_zombie", <travelersbackpack:travelers_backpack:75>, [[<sevendaystomine:cloth>, <minecraft:skull:2>, <sevendaystomine:cloth>], [<minecraft:rotten_flesh>, <travelersbackpack:travelers_backpack:*>, <minecraft:rotten_flesh>], [<minecraft:rotten_flesh>, <sevendaystomine:cloth>, <minecraft:rotten_flesh>]]);
recipes.addShaped("backpack_modded_network", <travelersbackpack:travelers_backpack:76>, [[<openblocks:dev_null>, <theoneprobe:probe>, <pvj:sugarcane_juice>], [<techguns:itemshared:66>, <travelersbackpack:travelers_backpack:*>, <sevendaystomine:gear>], [<buildcraftsilicon:redstone_chipset:3>, <oe:glow_ink_sac>, <netherex:dull_mirror>]]);


