#priority 1
//File created by Nykrdaudr
//removing bloat from JEI
//reccomplex

mods.jei.JEI.removeAndHide(<reccomplex:artifact_generation_tag>);
mods.jei.JEI.removeAndHide(<reccomplex:block_selector>);
mods.jei.JEI.removeAndHide(<reccomplex:block_selector_floating>);
mods.jei.JEI.removeAndHide(<reccomplex:book_generation_tag>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:1>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:2>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:3>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:4>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:5>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:6>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:7>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:8>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:9>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:10>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:11>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:12>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:13>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:14>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_solid:15>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:1>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:2>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:3>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:4>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:5>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:6>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:7>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:8>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:9>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:10>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:11>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:12>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:13>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:14>);
mods.jei.JEI.removeAndHide(<reccomplex:generic_space:15>);
mods.jei.JEI.removeAndHide(<reccomplex:inspector>);
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>);
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "AbandonedBurnable"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "AbandonedChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "AirShrine"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "CultArmory"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "CultTreasure"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "EarthShrine"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "FireShrine"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "ForestChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "Holy"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "MesoStorageChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "PeacefulCrypt"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "PirateChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "PyramidChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "PyramidGraveGoodsCheap"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "RichVillageHouse"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "TribalChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "UnderwaterShrine"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "Unholy"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "VillageGuardTower"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "VillageKitchen"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "VillageLibrary"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "VillagePumpkinChandlery"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "VillageTannery"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "WheatFieldMill"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "WheatFieldMillTools"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_component_tag>.withTag({itemCollectionKey: "WoodStorage"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "AbandonedBurnable"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "AbandonedChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "AirShrine"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "CultArmory"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "CultTreasure"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "EarthShrine"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "FireShrine"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "ForestChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "Holy"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "MesoStorageChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "PeacefulCrypt"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "PirateChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "PyramidChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "PyramidGraveGoodsCheap"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "RichVillageHouse"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "TribalChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "UnderwaterShrine"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "Unholy"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "VillageGuardTower"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "VillageKitchen"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "VillageLibrary"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "VillagePumpkinChandlery"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "VillageTannery"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "WheatFieldMill"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "WheatFieldMillTools"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "WoodStorage"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/abandoned_mineshaft"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/desert_pyramid"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/end_city_treasure"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/igloo_chest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/jungle_temple"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/jungle_temple_dispenser"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/nether_bridge"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/simple_dungeon"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/spawn_bonus_chest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/stronghold_corridor"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/stronghold_crossing"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/stronghold_library"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/village_blacksmith"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:chests/woodland_mansion"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:empty"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/bat"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/blaze"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/cave_spider"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/chicken"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/cow"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/creeper"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/donkey"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/elder_guardian"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/ender_dragon"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/enderman"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/endermite"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/evocation_illager"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/ghast"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/giant"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/guardian"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/horse"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/husk"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/iron_golem"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/llama"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/magma_cube"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/mule"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/mushroom_cow"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/ocelot"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/parrot"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/pig"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/polar_bear"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/rabbit"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/black"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/blue"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/brown"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/cyan"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/gray"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/green"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/light_blue"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/lime"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/magenta"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/orange"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/pink"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/purple"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/red"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/silver"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/white"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/yellow"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/shulker"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/silverfish"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/skeleton"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/skeleton_horse"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/slime"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/snowman"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/spider"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/squid"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/stray"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/vex"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/villager"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/vindication_illager"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/witch"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/wither_skeleton"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/wolf"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/zombie"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/zombie_horse"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/zombie_pigman"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:entities/zombie_villager"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:gameplay/fishing"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:gameplay/fishing/fish"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:gameplay/fishing/junk"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "minecraft:gameplay/fishing/treasure"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/brute"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/coolmar_spider"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/ember"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/frost"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/ghast/ghast"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/ghast/ghast_queen"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/ghast/ghastling"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/gold_golem"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/mogus/brown_mogus"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/mogus/red_mogus"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/mogus/white_mogus"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/nethermite"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_armorsmith"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_brewer"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_chief"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_enchanter"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_gatherer"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_hunter"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_nincompoop"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_scavenger"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_toolsmith"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/salamander/black_salamander"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/salamander/orange_salamander"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/spinout"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/spore"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/spore_creeper"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/wight"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "netherex:entity/wither_skeleton"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "openblocks:inject/technicolor_glasses"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "quark:entities/crab"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "quark:entities/foxhound"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "quark:entities/frog"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:airdrop"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:backpack"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:body_bag"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:bookshelf_common"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:bookshelf_rare"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:cardboard"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:cash_register"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:code_safe"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:coffin"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:cupboard"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:dresser"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:file_cabinet"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:fridge"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:furnace"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:medical_cabinet"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:microwave"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:nest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:police_car"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:sedan"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:shower_drain"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:sink"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:supply_chest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:toilet"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:trapped_chest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:trash"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:writing_table"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:zombie_feral"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:zombie_generic"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:zombie_miner"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:zombie_nurse"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:zombie_policeman"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "sevendaystomine:zombie_soldier"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "techguns:blocks/military_crate_ammo"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "techguns:blocks/military_crate_armor"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "techguns:blocks/military_crate_explosives"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "techguns:blocks/military_crate_generic"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "techguns:blocks/military_crate_gun"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_single_tag>.withTag({itemCollectionKey: "techguns:blocks/military_crate_medical"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "AbandonedBurnable"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "AbandonedChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "AirShrine"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "CultArmory"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "CultTreasure"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "EarthShrine"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "FireShrine"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "ForestChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "Holy"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "MesoStorageChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "PeacefulCrypt"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "PirateChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "PyramidChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "PyramidGraveGoodsCheap"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "RichVillageHouse"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "TribalChest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "UnderwaterShrine"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "Unholy"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "VillageGuardTower"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "VillageKitchen"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "VillageLibrary"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "VillagePumpkinChandlery"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "VillageTannery"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "WheatFieldMill"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "WheatFieldMillTools"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "WoodStorage"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/abandoned_mineshaft"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/desert_pyramid"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/end_city_treasure"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/igloo_chest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/jungle_temple"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/jungle_temple_dispenser"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/nether_bridge"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/simple_dungeon"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/spawn_bonus_chest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/stronghold_corridor"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/stronghold_crossing"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/stronghold_library"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/village_blacksmith"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:chests/woodland_mansion"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:empty"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/bat"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/blaze"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/cave_spider"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/chicken"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/cow"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/creeper"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/donkey"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/elder_guardian"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/ender_dragon"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/enderman"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/endermite"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/evocation_illager"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/ghast"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/giant"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/guardian"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/horse"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/husk"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/iron_golem"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/llama"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/magma_cube"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/mule"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/mushroom_cow"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/ocelot"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/parrot"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/pig"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/polar_bear"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/rabbit"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/black"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/blue"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/brown"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/cyan"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/gray"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/green"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/light_blue"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/lime"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/magenta"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/orange"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/pink"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/purple"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/red"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/silver"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/white"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/sheep/yellow"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/shulker"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/silverfish"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/skeleton"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/skeleton_horse"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/slime"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/snowman"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/spider"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/squid"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/stray"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/vex"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/villager"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/vindication_illager"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/witch"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/wither_skeleton"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/wolf"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/zombie"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/zombie_horse"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/zombie_pigman"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:entities/zombie_villager"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:gameplay/fishing"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:gameplay/fishing/fish"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:gameplay/fishing/junk"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "minecraft:gameplay/fishing/treasure"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/brute"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/coolmar_spider"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/ember"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/frost"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/ghast/ghast"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/ghast/ghast_queen"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/ghast/ghastling"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/gold_golem"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/mogus/brown_mogus"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/mogus/red_mogus"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/mogus/white_mogus"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/nethermite"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_armorsmith"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_brewer"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_chief"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_enchanter"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_gatherer"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_hunter"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_nincompoop"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_scavenger"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/pigtificate/pigtificate_toolsmith"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/salamander/black_salamander"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/salamander/orange_salamander"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/spinout"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/spore"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/spore_creeper"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/wight"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "netherex:entity/wither_skeleton"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "openblocks:inject/technicolor_glasses"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "quark:entities/crab"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "quark:entities/foxhound"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "quark:entities/frog"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:airdrop"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:backpack"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:body_bag"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:bookshelf_common"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:bookshelf_rare"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:cardboard"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:cash_register"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:code_safe"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:coffin"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:cupboard"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:dresser"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:file_cabinet"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:fridge"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:furnace"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:medical_cabinet"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:microwave"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:nest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:police_car"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:sedan"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:shower_drain"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:sink"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:supply_chest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:toilet"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:trapped_chest"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:trash"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:writing_table"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:zombie_feral"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:zombie_generic"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:zombie_miner"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:zombie_nurse"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:zombie_policeman"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "sevendaystomine:zombie_soldier"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "techguns:blocks/military_crate_ammo"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "techguns:blocks/military_crate_armor"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "techguns:blocks/military_crate_explosives"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "techguns:blocks/military_crate_generic"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "techguns:blocks/military_crate_gun"}));
mods.jei.JEI.removeAndHide(<reccomplex:inventory_generation_tag>.withTag({itemCollectionKey: "techguns:blocks/military_crate_medical"}));