#priority 1
// File created by Nykrdaudr
//Hiding bloat from JEI


// mods.jei.JEI.hide - hides item
// mods.jei.JEI.removeAndHide - hides item + crafts (bool for nbt match)
// mods-jei.JEI.hideCategory - hides everything from a crafting station

//============================================================================================================================================================================================
//============================================================================================================================================================================================
//HIDING CRAFTING STATIONS
//============================================================================================================================================================================================
//============================================================================================================================================================================================
mods.jei.JEI.hideCategory("fluid_processor");
mods.jei.JEI.hideCategory("Electrolytic Cell");
mods.jei.JEI.hideCategory("buildcraft-compat:silicon.assembly");
mods.jei.JEI.hideCategory("Chemistry Station");
mods.jei.JEI.hideCategory("techguns.camobench");

//============================================================================================================================================================================================
//============================================================================================================================================================================================
//HIDE UNCRAFTABLE ITEMS
//============================================================================================================================================================================================
//============================================================================================================================================================================================
mods.jei.JEI.hide(<minecraft:brown_mushroom_block>);
mods.jei.JEI.hide(<minecraft:red_mushroom_block>);
mods.jei.JEI.hide(<minecraft:fireworks>);
mods.jei.JEI.hide(<netherex:netherrack_path>);
mods.jei.JEI.hide(<netherex:gloomy_netherrack_path>);
mods.jei.JEI.hide(<netherex:lively_netherrack_path>);
mods.jei.JEI.hide(<netherex:fiery_netherrack_path>);
mods.jei.JEI.hide(<netherex:icy_netherrack_path>);
mods.jei.JEI.hide(<netherex:brown_elder_mushroom_cap>);
mods.jei.JEI.hide(<netherex:red_elder_mushroom_cap>);
mods.jei.JEI.hide(<netherex:enoki_mushroom_cap>);
mods.jei.JEI.hide(<netherex:elder_mushroom_stem>);
mods.jei.JEI.hide(<netherex:enoki_mushroom_stem>);
mods.jei.JEI.hide(<oe:blue_coral_block_dead>);
mods.jei.JEI.hide(<oe:pink_coral_block_dead>);
mods.jei.JEI.hide(<oe:purple_coral_block_dead>);
mods.jei.JEI.hide(<oe:red_coral_block_dead>);
mods.jei.JEI.hide(<oe:yellow_coral_block_dead>);
mods.jei.JEI.hide(<oe:blue_coral_fan_dead>);
mods.jei.JEI.hide(<oe:pink_coral_fan_dead>);
mods.jei.JEI.hide(<oe:purple_coral_fan_dead>);
mods.jei.JEI.hide(<oe:red_coral_fan_dead>);
mods.jei.JEI.hide(<oe:yellow_coral_fan_dead>);
mods.jei.JEI.hide(<oe:blue_coral_dead>);
mods.jei.JEI.hide(<oe:pink_coral_dead>);
mods.jei.JEI.hide(<oe:purple_coral_dead>);
mods.jei.JEI.hide(<oe:red_coral_dead>);
mods.jei.JEI.hide(<oe:yellow_coral_dead>);
mods.jei.JEI.hide(<oe:seastar>);
mods.jei.JEI.hide(<quark:glowshroom_block>);
mods.jei.JEI.hide(<baubles:ring>);
mods.jei.JEI.hide(<openblocks:xp_bucket>);
mods.jei.JEI.hide(<malisisdoors:customdooritem>);
/*
ugly textures in "parasitus core"
mods.jei.JEI.hide(<pvj:willow_door_item>);
mods.jei.JEI.hide(<pvj:mangrove_door_item>);
mods.jei.JEI.hide(<pvj:palm_door_item>);
mods.jei.JEI.hide(<pvj:redwood_door_item>);
mods.jei.JEI.hide(<pvj:fir_door_item>);
mods.jei.JEI.hide(<pvj:pine_door_item>);
mods.jei.JEI.hide(<pvj:aspen_door_item>);
mods.jei.JEI.hide(<pvj:maple_door_item>);
mods.jei.JEI.hide(<pvj:baobab_door_item>);
mods.jei.JEI.hide(<pvj:cottonwood_door_item>);
mods.jei.JEI.hide(<pvj:juniper_door_item>);
mods.jei.JEI.hide(<pvj:cherry_blossom_door_item>);
mods.jei.JEI.hide(<pvj:jacaranda_door_item>);
mods.jei.JEI.hide(<techguns:item_bunkerdoor>);
*/
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_brass.cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_bronze.cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_copper.cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_diamond_steel.cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_lead.cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_obsidian_steel.cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_steel.cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_tin.cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_titanium.cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_uranium.cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_zinc.cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil_heavy", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil_dense", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "bcop-gold-cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "ichor", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "bcop-gaseous_lava-cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil_distilled", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_dense", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_light", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_gaseous", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_mixed_heavy", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "bcop-iron-cool", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_mixed_light", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "xpjuice", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_brass.hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_bronze.hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_copper.hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_diamond_steel.hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_lead.hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_obsidian_steel.hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_steel.hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_tin.hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_titanium.hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_uranium.hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_zinc.hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil_heavy_heat_1", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil_dense_heat_1", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "bcop-gold-hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil_heat_1", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "bcop-gaseous_lava-hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil_distilled_heat_1", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_dense_heat_1", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_light_heat_1", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_gaseous_heat_1", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_mixed_heavy_heat_1", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "bcop-iron-hot", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_mixed_light_heat_1", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_brass.searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_bronze.searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_copper.searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_diamond_steel.searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_lead.searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_obsidian_steel.searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_steel.searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_tin.searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_titanium.searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_uranium.searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "molten_zinc.searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil_heavy_heat_2", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil_dense_heat_2", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "bcop-gold-searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil_heat_2", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "bcop-gaseous_lava-searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil_distilled_heat_2", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_dense_heat_2", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_light_heat_2", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_mixed_heavy_heat_2", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "bcop-iron-searing", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_mixed_light_heat_2", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "oil_residue_heat_2", Amount: 1000}));
mods.jei.JEI.hide(<forge:bucketfilled>.withTag({FluidName: "fuel_gaseous_heat_2", Amount: 1000}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "ichor", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "potion", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "bcop-gaseous_lava-hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_heat_1", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_gaseous_heat_1", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_light_heat_2", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_dense_heat_2", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_heavy_heat_2", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_lead.searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_brass.searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_bronze.hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "lava", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_dense_heat_1", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_mixed_heavy_heat_2", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_heavy_heat_1", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "deadblood", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_lead.hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_obsidian_steel.searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_gaseous_heat_2", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_uranium.hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_tin.searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_light_heat_1", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_residue_heat_1", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_steel.searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "bcop-gold-hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "gasoline", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "mercury", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_copper.cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_obsidian_steel.hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_dense_heat_1", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_zinc.searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "bcop-iron-hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_copper.hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_dense", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "bcop-gold-searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_mixed_heavy", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_heat_2", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_residue", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_steel.cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "water", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_brass.cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_dense_heat_2", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_uranium.searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_heavy", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_bronze.cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "milk", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_obsidian_steel.cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_mixed_light_heat_1", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "bcop-iron-cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_zinc.hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "xpjuice", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "bcop-gaseous_lava-searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_dense", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "bcop-iron-searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_distilled_heat_1", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_diamond_steel.hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_titanium.hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_bronze.searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_steel.hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_diamond_steel.cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_copper.searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_mixed_light", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_tin.hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_light", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_residue_heat_2", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_brass.hot", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "bcop-gaseous_lava-cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_titanium.searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_gaseous", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_diamond_steel.searing", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_distilled", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_lead.cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "oil_distilled_heat_2", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "creeper_acid", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_titanium.cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_tin.cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_zinc.cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "bcop-gold-cool", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_mixed_light_heat_2", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "fuel_mixed_heavy_heat_1", Amount: 16000}}));
mods.jei.JEI.hide(<openblocks:tank>.withTag({tank: {FluidName: "molten_uranium.cool", Amount: 16000}}));
mods.jei.JEI.hide(<liquid:molten_bronze.searing>);
mods.jei.JEI.hide(<liquid:molten_bronze.hot>);
mods.jei.JEI.hide(<liquid:molten_bronze.cool>);
mods.jei.JEI.hide(<liquid:molten_brass.searing>);
mods.jei.JEI.hide(<liquid:molten_brass.hot>);
mods.jei.JEI.hide(<liquid:molten_brass.cool>);
mods.jei.JEI.hide(<liquid:molten_obsidian_steel.searing>);
mods.jei.JEI.hide(<liquid:molten_obsidian_steel.hot>);
mods.jei.JEI.hide(<liquid:molten_obsidian_steel.cool>);
mods.jei.JEI.hide(<liquid:molten_titanium.searing>);
mods.jei.JEI.hide(<liquid:molten_uranium.searing>);
mods.jei.JEI.hide(<liquid:molten_diamond_steel.searing>);
mods.jei.JEI.hide(<liquid:molten_titanium.hot>);
mods.jei.JEI.hide(<liquid:molten_uranium.hot>);
mods.jei.JEI.hide(<liquid:molten_diamond_steel.hot>);
mods.jei.JEI.hide(<liquid:molten_titanium.cool>);
mods.jei.JEI.hide(<liquid:molten_uranium.cool>);
mods.jei.JEI.hide(<liquid:molten_diamond_steel.cool>);

//============================================================================================================================================================================================
//============================================================================================================================================================================================
//REMOVING BLOAT
//============================================================================================================================================================================================
//============================================================================================================================================================================================
//VANILLA
mods.jei.JEI.removeAndHide(<minecraft:iron_shovel>, false);
mods.jei.JEI.removeAndHide(<minecraft:iron_pickaxe>, false);
mods.jei.JEI.removeAndHide(<minecraft:iron_axe>, false);
mods.jei.JEI.removeAndHide(<minecraft:iron_sword>, false);
mods.jei.JEI.removeAndHide(<minecraft:wooden_sword>, false);
mods.jei.JEI.removeAndHide(<minecraft:wooden_shovel>, false);
mods.jei.JEI.removeAndHide(<minecraft:wooden_pickaxe>, false);
mods.jei.JEI.removeAndHide(<minecraft:wooden_axe>, false);
mods.jei.JEI.removeAndHide(<minecraft:wooden_hoe>, false);
mods.jei.JEI.removeAndHide(<minecraft:stone_sword>, false);
mods.jei.JEI.removeAndHide(<minecraft:stone_shovel>, false);
mods.jei.JEI.removeAndHide(<minecraft:stone_pickaxe>, false);
mods.jei.JEI.removeAndHide(<minecraft:stone_axe>, false);
mods.jei.JEI.removeAndHide(<minecraft:stone_hoe>, false);
mods.jei.JEI.removeAndHide(<minecraft:diamond_sword>, false);
mods.jei.JEI.removeAndHide(<minecraft:diamond_shovel>, false);
mods.jei.JEI.removeAndHide(<minecraft:diamond_pickaxe>, false);
mods.jei.JEI.removeAndHide(<minecraft:diamond_axe>, false);
mods.jei.JEI.removeAndHide(<minecraft:golden_sword>, false);
mods.jei.JEI.removeAndHide(<minecraft:golden_shovel>, false);
mods.jei.JEI.removeAndHide(<minecraft:golden_pickaxe>, false);
mods.jei.JEI.removeAndHide(<minecraft:golden_axe>, false);
mods.jei.JEI.removeAndHide(<minecraft:golden_hoe>, false);
mods.jei.JEI.removeAndHide(<minecraft:leather_helmet>, false);
mods.jei.JEI.removeAndHide(<minecraft:leather_chestplate>, false);
mods.jei.JEI.removeAndHide(<minecraft:leather_leggings>, false);
mods.jei.JEI.removeAndHide(<minecraft:leather_boots>, false);
mods.jei.JEI.removeAndHide(<minecraft:chainmail_helmet>, false);
mods.jei.JEI.removeAndHide(<minecraft:chainmail_chestplate>, false);
mods.jei.JEI.removeAndHide(<minecraft:chainmail_leggings>, false);
mods.jei.JEI.removeAndHide(<minecraft:chainmail_boots>, false);
mods.jei.JEI.removeAndHide(<minecraft:iron_helmet>, false);
mods.jei.JEI.removeAndHide(<minecraft:iron_chestplate>, false);
mods.jei.JEI.removeAndHide(<minecraft:iron_leggings>, false);
mods.jei.JEI.removeAndHide(<minecraft:iron_boots>, false);
mods.jei.JEI.removeAndHide(<minecraft:diamond_helmet>, false);
mods.jei.JEI.removeAndHide(<minecraft:diamond_chestplate>, false);
mods.jei.JEI.removeAndHide(<minecraft:diamond_leggings>, false);
mods.jei.JEI.removeAndHide(<minecraft:diamond_boots>, false);
mods.jei.JEI.removeAndHide(<minecraft:golden_helmet>, false);
mods.jei.JEI.removeAndHide(<minecraft:golden_chestplate>, false);
mods.jei.JEI.removeAndHide(<minecraft:golden_leggings>, false);
mods.jei.JEI.removeAndHide(<minecraft:golden_boots>, false);
mods.jei.JEI.removeAndHide(<minecraft:totem_of_undying>);
mods.jei.JEI.removeAndHide(<minecraft:mob_spawner>);
mods.jei.JEI.removeAndHide(<minecraft:farmland>);
mods.jei.JEI.removeAndHide(<minecraft:command_block>);
mods.jei.JEI.removeAndHide(<minecraft:barrier>);
mods.jei.JEI.removeAndHide(<minecraft:grass_path>);
mods.jei.JEI.removeAndHide(<minecraft:repeating_command_block>);
mods.jei.JEI.removeAndHide(<minecraft:chain_command_block>);
mods.jei.JEI.removeAndHide(<minecraft:structure_void>);
mods.jei.JEI.removeAndHide(<minecraft:structure_block>);
mods.jei.JEI.removeAndHide(<minecraft:knowledge_book>);
mods.jei.JEI.removeAndHide(<minecraft:command_block_minecart>);
mods.jei.JEI.removeAndHide(<minecraft:bedrock>);
//============================================================================================================================================================================================
//BOOKS
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 0 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 0 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 0 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 1 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 1 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 1 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 2 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 2 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 2 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 3 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 3 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 3 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 4 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 4 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 4 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 5 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 5 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 7 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 7 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 8 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 8 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 9 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 11 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 11 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 11 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 11 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 15 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 15 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 15 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 15 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 16 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 16 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 16 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 16 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 17 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 17 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 17 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 17 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 18 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 18 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 18 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 18 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 19 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 20 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 21 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 21 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 22 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 22 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 23 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 23 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 23 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 23 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 24 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 24 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 24 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 24 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 27 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 29 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 29 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 29 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 29 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 30 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 30 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 31 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 32 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 32 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 32 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 32 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 34 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 34 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 35 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 35 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 36 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 36 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 37 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 37 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 37 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 38 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 38 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 38 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 38 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 39 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 39 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 40 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 40 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 41 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 41 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 41 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 41 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 43 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 43 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 45 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 46 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 47 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 47 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 48 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 48 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 48 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 48 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 49 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 52 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 52 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 54 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 54 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 58 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 56 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 56 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 61 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 61 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 62 as short}]}));
mods.jei.JEI.hide(<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 62 as short}]}));
//============================================================================================================================================================================================
//7DTM
mods.jei.JEI.removeAndHide(<sevendaystomine:separator>);
mods.jei.JEI.removeAndHide(<sevendaystomine:turret_base>);
mods.jei.JEI.removeAndHide(<sevendaystomine:turret_advanced>);
mods.jei.JEI.removeAndHide(<sevendaystomine:landmine>);
mods.jei.JEI.removeAndHide(<sevendaystomine:wheels>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:wind_turbine>);
mods.jei.JEI.removeAndHide(<sevendaystomine:battery_station>);
mods.jei.JEI.removeAndHide(<sevendaystomine:flamethrower_trap>);
mods.jei.JEI.removeAndHide(<sevendaystomine:spikedclub>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:armyknife>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:auger>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:minibike_chassis>);
mods.jei.JEI.removeAndHide(<sevendaystomine:minibike_handles>);
mods.jei.JEI.removeAndHide(<sevendaystomine:minibike_seat>);
mods.jei.JEI.removeAndHide(<sevendaystomine:steel_helmet>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:steel_chestplate>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:steel_leggings>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:steel_boots>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:backpack>);
mods.jei.JEI.removeAndHide(<sevendaystomine:leather_iron_helmet>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:leather_iron_chestplate>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:leather_iron_boots>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:leather_iron_leggings>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:chainsaw>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:scrap_shovel>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:copper_shovel>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:copper_pickaxe>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:copper_axe>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:bronze_shovel>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:bronze_pickaxe>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:bronze_axe>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:pistol_slide>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:pistol_trigger>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:pistol_grip>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:sniper_rifle_barrel>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:sniper_rifle_scope>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:sniper_rifle_stock>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:sniper_rifle_trigger>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:iron_helmet>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:iron_chestplate>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:iron_leggings>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:iron_boots>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:leather_helmet>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:leather_chestplate>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:leather_leggings>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:leather_boots>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:military_helmet>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:military_chestplate>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:military_leggings>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:military_boots>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:sniper_rifle>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:pistol>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:ak47>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:hunting_rifle>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:shotgun>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:shotgun_short>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:shotgun_barrel>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:shotgun_barrel_short>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:shotgun_parts>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:shotgun_receiver>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:shotgun_stock>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:shotgun_stock_short>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:magnum>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:magnum_scoped>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:flamethrower>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:mp5>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:rpg>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:m4>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:magnum_frame>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:magnum_cylinder>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:magnum_grip>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:mp5_barrel>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:mp5_stock>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:mp5_trigger>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:auger_blade>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:night_vision_device>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:christmas_hat>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:beret>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:copper_hoe>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:bronze_hoe>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:auger_handles>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:hunting_rifle_barrel>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:hunting_rifle_bolt>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:hunting_rifle_parts>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:hunting_rifle_stock>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:book_ammo>);
mods.jei.JEI.removeAndHide(<sevendaystomine:magnet>);
mods.jei.JEI.removeAndHide(<sevendaystomine:book_pistol>);
mods.jei.JEI.removeAndHide(<sevendaystomine:book_minibike>);
mods.jei.JEI.removeAndHide(<sevendaystomine:book_shotgun>);
mods.jei.JEI.removeAndHide(<sevendaystomine:book_sniper>);
mods.jei.JEI.removeAndHide(<sevendaystomine:bullet_10mm>);
mods.jei.JEI.removeAndHide(<sevendaystomine:sevenmmbullet>);
mods.jei.JEI.removeAndHide(<sevendaystomine:ninemmbullet>);
mods.jei.JEI.removeAndHide(<sevendaystomine:bullet_magnum>);
mods.jei.JEI.removeAndHide(<sevendaystomine:book_magnum>);
mods.jei.JEI.removeAndHide(<sevendaystomine:book_mp5>);
mods.jei.JEI.removeAndHide(<sevendaystomine:book_hunting_rifle>);
mods.jei.JEI.removeAndHide(<sevendaystomine:shotgun_shell>);
mods.jei.JEI.removeAndHide(<sevendaystomine:book_auger>);
mods.jei.JEI.removeAndHide(<sevendaystomine:hunting_rifle_barrel_mold>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:hunting_rifle_bolt_mold>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:mp5_stock_mold>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:mp5_barrel_mold>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:mp5_trigger_mold>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:pistol_barrel_mold>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:pistol_trigger_mold>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:sniper_rifle_stock_mold>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:sniper_rifle_trigger_mold>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:shotgun_barrel_mold>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:shotgun_receiver_mold>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:shotgun_short_barrel_mold>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:chlorine_tank>);
mods.jei.JEI.removeAndHide(<sevendaystomine:natrium_tank>);
mods.jei.JEI.removeAndHide(<sevendaystomine:chlorine_grenade>);
mods.jei.JEI.removeAndHide(<sevendaystomine:fragmentation_grenade>);
mods.jei.JEI.removeAndHide(<sevendaystomine:riot_shield>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:rocket>);
mods.jei.JEI.removeAndHide(<sevendaystomine:car_chassis>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:book_rocket>);
mods.jei.JEI.removeAndHide(<sevendaystomine:flare>);
mods.jei.JEI.removeAndHide(<sevendaystomine:sniper_rifle_parts>, false);
mods.jei.JEI.removeAndHide(<sevendaystomine:chemistry_station>);
mods.jei.JEI.removeAndHide(<sevendaystomine:smallrock:0>);
mods.jei.JEI.removeAndHide(<sevendaystomine:smallrock:1>);
mods.jei.JEI.removeAndHide(<sevendaystomine:smallrock:2>);
mods.jei.JEI.removeAndHide(<sevendaystomine:smallrock:3>);
mods.jei.JEI.removeAndHide(<sevendaystomine:torchlit>);
mods.jei.JEI.removeAndHide(<sevendaystomine:large_rock>);
mods.jei.JEI.removeAndHide(<sevendaystomine:airplane_rotor>);
mods.jei.JEI.removeAndHide(<sevendaystomine:stick>);
mods.jei.JEI.removeAndHide(<sevendaystomine:bush>);
mods.jei.JEI.removeAndHide(<sevendaystomine:campfire_lit>);
mods.jei.JEI.removeAndHide(<sevendaystomine:forge_lit>);
mods.jei.JEI.removeAndHide(<sevendaystomine:coffeeplant>);
mods.jei.JEI.removeAndHide(<sevendaystomine:blueberryplant>);
mods.jei.JEI.removeAndHide(<sevendaystomine:baneberryplant>);
mods.jei.JEI.removeAndHide(<sevendaystomine:sedan_red>);
mods.jei.JEI.removeAndHide(<sevendaystomine:sedan_green>);
mods.jei.JEI.removeAndHide(<sevendaystomine:sedan_blue>);
mods.jei.JEI.removeAndHide(<sevendaystomine:sedan_yellow>);
mods.jei.JEI.removeAndHide(<sevendaystomine:sedan_white>);
mods.jei.JEI.removeAndHide(<sevendaystomine:sedan_black>);
mods.jei.JEI.removeAndHide(<sevendaystomine:monitor_mac>);
mods.jei.JEI.removeAndHide(<sevendaystomine:monitor_linux>);
mods.jei.JEI.removeAndHide(<sevendaystomine:monitor_win98>);
mods.jei.JEI.removeAndHide(<sevendaystomine:monitor_winxp>);
mods.jei.JEI.removeAndHide(<sevendaystomine:monitor_win7>);
mods.jei.JEI.removeAndHide(<sevendaystomine:monitor_win8>);
mods.jei.JEI.removeAndHide(<sevendaystomine:monitor_win10>);
mods.jei.JEI.removeAndHide(<sevendaystomine:wooden_spikes_blooded>);
mods.jei.JEI.removeAndHide(<sevendaystomine:wooden_spikes_broken>);
mods.jei.JEI.removeAndHide(<sevendaystomine:police_car>);
mods.jei.JEI.removeAndHide(<sevendaystomine:paper>);
mods.jei.JEI.removeAndHide(<sevendaystomine:ambulance>);
mods.jei.JEI.removeAndHide(<sevendaystomine:realitywand>);
mods.jei.JEI.removeAndHide(<sevendaystomine:photo>);
mods.jei.JEI.removeAndHide(<sevendaystomine:vomit>);
mods.jei.JEI.removeAndHide(<sevendaystomine:kitchenknife>);
mods.jei.JEI.removeAndHide(<sevendaystomine:car_battery>);
mods.jei.JEI.removeAndHide(<sevendaystomine:small_engine>);
mods.jei.JEI.removeAndHide(<sevendaystomine:bloodmoon>);
//============================================================================================================================================================================================
//BUILDCRAFT
mods.jei.JEI.removeAndHide(<buildcraftcore:decorated:0>);
mods.jei.JEI.removeAndHide(<buildcraftcore:decorated:1>);
mods.jei.JEI.removeAndHide(<buildcraftcore:decorated:2>);
mods.jei.JEI.removeAndHide(<buildcraftcore:decorated:3>);
mods.jei.JEI.removeAndHide(<buildcraftcore:decorated:4>);
mods.jei.JEI.removeAndHide(<buildcraftcore:decorated:5>);
mods.jei.JEI.removeAndHide(<buildcraftcore:marker_path>);
mods.jei.JEI.removeAndHide(<buildcraftcore:map_location>);
mods.jei.JEI.removeAndHide(<buildcraftbuilders:snapshot:0>);
mods.jei.JEI.removeAndHide(<buildcraftbuilders:snapshot:2>);
mods.jei.JEI.removeAndHide(<buildcraftbuilders:schematic_single>);
mods.jei.JEI.removeAndHide(<buildcraftbuilders:filler_planner>);
mods.jei.JEI.removeAndHide(<buildcraftbuilders:filler>);
mods.jei.JEI.removeAndHide(<buildcraftbuilders:replacer>);
mods.jei.JEI.removeAndHide(<buildcraftsilicon:laser>);
mods.jei.JEI.removeAndHide(<buildcraftsilicon:assembly_table>);
mods.jei.JEI.removeAndHide(<buildcraftsilicon:advanced_crafting_table>);
mods.jei.JEI.removeAndHide(<buildcraftsilicon:integration_table>);
mods.jei.JEI.removeAndHide(<bcoreprocessing:fluid_processor>);
mods.jei.JEI.removeAndHide(<buildcraftcore:spring:0>);
mods.jei.JEI.removeAndHide(<buildcraftcore:spring:1>);
mods.jei.JEI.removeAndHide(<buildcraftcore:volume_box>);
mods.jei.JEI.removeAndHide(<buildcraftbuilders:frame>);
mods.jei.JEI.removeAndHide(<buildcraftbuilders:builder>);
mods.jei.JEI.removeAndHide(<buildcraftbuilders:architect>);
mods.jei.JEI.removeAndHide(<buildcraftbuilders:library>);
mods.jei.JEI.removeAndHide(<buildcraftenergy:glob_of_oil>);
mods.jei.JEI.removeAndHide(<buildcraftlib:debugger>);
mods.jei.JEI.removeAndHide(<buildcraftrobotics:zone_planner>);
mods.jei.JEI.removeAndHide(<buildcraftcore:engine:3>);
mods.jei.JEI.removeAndHide(<buildcraftlib:guide>.withTag({BookName: "buildcraftlib:meta"}));
mods.jei.JEI.removeAndHide(<buildcraftlib:guide_note>);
//============================================================================================================================================================================================
//TECHGUNS
mods.jei.JEI.removeAndHide(<techguns:basicmachine:3>);
mods.jei.JEI.removeAndHide(<techguns:bioblob>);
mods.jei.JEI.removeAndHide(<techguns:tg_spawner>);
mods.jei.JEI.removeAndHide(<techguns:tg_spawner:1>);
mods.jei.JEI.removeAndHide(<techguns:slimy>);
mods.jei.JEI.removeAndHide(<techguns:itemshared:25>);
mods.jei.JEI.removeAndHide(<techguns:itemshared:26>);
mods.jei.JEI.removeAndHide(<techguns:itemshared:41>);
mods.jei.JEI.removeAndHide(<techguns:itemshared:71>);
mods.jei.JEI.removeAndHide(<techguns:itemshared:73>);
mods.jei.JEI.removeAndHide(<techguns:itemshared:99>);
mods.jei.JEI.removeAndHide(<techguns:itemshared:100>);
mods.jei.JEI.removeAndHide(<techguns:itemshared:101>);
mods.jei.JEI.removeAndHide(<techguns:itemshared:133>);
mods.jei.JEI.removeAndHide(<techguns:radaway>);
mods.jei.JEI.removeAndHide(<techguns:radpills>);
mods.jei.JEI.removeAndHide(<techguns:hazmat_helmet>, false);
mods.jei.JEI.removeAndHide(<techguns:hazmat_chestplate>, false);
mods.jei.JEI.removeAndHide(<techguns:hazmat_leggings>, false);
mods.jei.JEI.removeAndHide(<techguns:hazmat_boots>, false);
mods.jei.JEI.removeAndHide(<techguns:biogun>, false);
mods.jei.JEI.removeAndHide(<techguns:lasergun>, false);
mods.jei.JEI.removeAndHide(<techguns:blasterrifle>, false);
mods.jei.JEI.removeAndHide(<techguns:scatterbeamrifle>, false);
mods.jei.JEI.removeAndHide(<techguns:mibgun>, false);
mods.jei.JEI.removeAndHide(<techguns:alienblaster>, false);
mods.jei.JEI.removeAndHide(<techguns:nucleardeathray>, false);
mods.jei.JEI.removeAndHide(<techguns:laserpistol>, false);
mods.jei.JEI.removeAndHide(<techguns:itemshared:71>);
//mods.jei.JEI.removeAndHide(<techguns:simplemachine:8>);
//============================================================================================================================================================================================
//PROJECT VIBRANT JOURNEY
mods.jei.JEI.removeAndHide(<pvj:mystical_porkchop>);
mods.jei.JEI.removeAndHide(<pvj:mystical_beef>);
mods.jei.JEI.removeAndHide(<pvj:mystical_chicken>);
mods.jei.JEI.removeAndHide(<pvj:mystical_mutton>);
mods.jei.JEI.removeAndHide(<pvj:mystical_cod>);
mods.jei.JEI.removeAndHide(<pvj:mystical_salmon>);
mods.jei.JEI.removeAndHide(<pvj:mystical_potato>);
mods.jei.JEI.removeAndHide(<pvj:mystical_rabbit>);
mods.jei.JEI.removeAndHide(<pvj:unstable_essence>);
mods.jei.JEI.removeAndHide(<pvj:goon_bile>);
mods.jei.JEI.removeAndHide(<pvj:spectral_wrappings>);
mods.jei.JEI.removeAndHide(<pvj:mystical_grill>);
mods.jei.JEI.removeAndHide(<pvj:willow_door>);
mods.jei.JEI.removeAndHide(<pvj:mangrove_door>);
mods.jei.JEI.removeAndHide(<pvj:palm_door>);
mods.jei.JEI.removeAndHide(<pvj:redwood_door>);
mods.jei.JEI.removeAndHide(<pvj:fir_door>);
mods.jei.JEI.removeAndHide(<pvj:pine_door>);
mods.jei.JEI.removeAndHide(<pvj:aspen_door>);
mods.jei.JEI.removeAndHide(<pvj:maple_door>);
mods.jei.JEI.removeAndHide(<pvj:baobab_door>);
mods.jei.JEI.removeAndHide(<pvj:cottonwood_door>);
mods.jei.JEI.removeAndHide(<pvj:juniper_door>);
mods.jei.JEI.removeAndHide(<pvj:cherry_blossom_door>);
mods.jei.JEI.removeAndHide(<pvj:jacaranda_door>);
mods.jei.JEI.removeAndHide(<pvj:pvj_cobweb>);
//============================================================================================================================================================================================
//OMNLIB
mods.jei.JEI.removeAndHide(<omlib:multi_tool>);
mods.jei.JEI.removeAndHide(<omlib:debug_tool>);
mods.jei.JEI.removeAndHide(<omlib:network_cable>);
mods.jei.JEI.removeAndHide(<omlib:fake_sword>);
//============================================================================================================================================================================================
//OPENBLOCKS
mods.jei.JEI.removeAndHide(<openblocks:guide>);
mods.jei.JEI.removeAndHide(<openblocks:builder_guide>);
mods.jei.JEI.removeAndHide(<openblocks:tasty_clay>);
mods.jei.JEI.removeAndHide(<openblocks:heal>);
mods.jei.JEI.removeAndHide(<openblocks:grave>);
mods.jei.JEI.removeAndHide(<openblocks:flag:5>);
mods.jei.JEI.removeAndHide(<openblocks:sprinkler>);
mods.jei.JEI.removeAndHide(<openblocks:cannon>);
mods.jei.JEI.removeAndHide(<openblocks:vacuum_hopper>);
mods.jei.JEI.removeAndHide(<openblocks:sponge>);
mods.jei.JEI.removeAndHide(<openblocks:fan>);
mods.jei.JEI.removeAndHide(<openblocks:block_breaker>);
mods.jei.JEI.removeAndHide(<openblocks:block_placer>);
mods.jei.JEI.removeAndHide(<openblocks:item_dropper>);
mods.jei.JEI.removeAndHide(<openblocks:donation_station>);
mods.jei.JEI.removeAndHide(<openblocks:projector>);
mods.jei.JEI.removeAndHide(<openblocks:hang_glider>);
mods.jei.JEI.removeAndHide(<openblocks:generic:0>);
mods.jei.JEI.removeAndHide(<openblocks:generic:1>);
mods.jei.JEI.removeAndHide(<openblocks:generic:2>);
mods.jei.JEI.removeAndHide(<openblocks:generic:3>);
mods.jei.JEI.removeAndHide(<openblocks:generic:4>);
mods.jei.JEI.removeAndHide(<openblocks:generic:5>);
mods.jei.JEI.removeAndHide(<openblocks:generic:6>);
mods.jei.JEI.removeAndHide(<openblocks:generic:7>);
mods.jei.JEI.removeAndHide(<openblocks:generic:9>);
mods.jei.JEI.removeAndHide(<openblocks:luggage>);
mods.jei.JEI.removeAndHide(<openblocks:crane_control>);
mods.jei.JEI.removeAndHide(<openblocks:crane_backpack>);
mods.jei.JEI.removeAndHide(<openblocks:sleeping_bag>);
mods.jei.JEI.removeAndHide(<openblocks:empty_map>.withTag({Scale: 0 as byte}));
mods.jei.JEI.removeAndHide(<openblocks:empty_map>.withTag({Scale: 1 as byte}));
mods.jei.JEI.removeAndHide(<openblocks:empty_map>.withTag({Scale: 2 as byte}));
mods.jei.JEI.removeAndHide(<openblocks:empty_map>.withTag({Scale: 3 as byte}));
mods.jei.JEI.removeAndHide(<openblocks:cartographer>);
mods.jei.JEI.removeAndHide(<openblocks:golden_eye>.withTag({}));
mods.jei.JEI.removeAndHide(<openblocks:golden_eye:100>.withTag({}));
mods.jei.JEI.removeAndHide(<openblocks:generic_unstackable:0>);
mods.jei.JEI.removeAndHide(<openblocks:cursor>);
mods.jei.JEI.removeAndHide(<openblocks:sponge_on_a_stick>);
mods.jei.JEI.removeAndHide(<openblocks:pedometer>);
mods.jei.JEI.removeAndHide(<openblocks:epic_eraser>);
mods.jei.JEI.removeAndHide(<openblocks:wrench>);
//============================================================================================================================================================================================
mods.jei.JEI.removeAndHide(<openblocks:imaginary>.withTag({Uses: 10.0 as float, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 1973019, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 11743532, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 3887386, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 5320730, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 2437522, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 8073150, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 2651799, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 11250603, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 4408131, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 14188952, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 4312372, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 14602026, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 6719955, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 12801229, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 15435844, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary:1>.withTag({Uses: 10.0 as float, Color: 15790320, Mode: 0}));
mods.jei.JEI.removeAndHide(<openblocks:imaginary>);
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 1973019}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 11743532}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 3887386}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 5320730}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 2437522}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 8073150}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 2651799}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 11250603}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 4408131}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 14188952}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 4312372}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 14602026}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 6719955}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 12801229}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 15435844}));
mods.jei.JEI.removeAndHide(<openblocks:crayon_glasses>.withTag({Color: 15790320}));
mods.jei.JEI.removeAndHide(<openblocks:technicolor_glasses>);
mods.jei.JEI.removeAndHide(<openblocks:serious_glasses>);
mods.jei.JEI.removeAndHide(<openblocks:pencil_glasses>);
//============================================================================================================================================================================================
mods.jei.JEI.removeAndHide(<openblocks:trophy>);
mods.jei.JEI.removeAndHide(<openblocks:trophy>.withTag({entity_id: "minecraft:wolf"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:1>.withTag({entity_id: "minecraft:chicken"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:2>.withTag({entity_id: "minecraft:cow"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:5>.withTag({entity_id: "minecraft:zombie_pigman"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:6>.withTag({entity_id: "minecraft:bat"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:10>.withTag({entity_id: "minecraft:ocelot"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:13>.withTag({entity_id: "minecraft:silverfish"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:19>.withTag({entity_id: "minecraft:magma_cube"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:21>.withTag({entity_id: "minecraft:mooshroom"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:22>.withTag({entity_id: "minecraft:villager_golem"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:23>.withTag({entity_id: "minecraft:snowman"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:24>.withTag({entity_id: "minecraft:pig"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:28>.withTag({entity_id: "minecraft:polar_bear"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:30>.withTag({entity_id: "minecraft:horse"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:31>.withTag({entity_id: "minecraft:skeleton_horse"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:32>.withTag({entity_id: "minecraft:zombie_horse"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:33>.withTag({entity_id: "minecraft:donkey"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:34>.withTag({entity_id: "minecraft:mule"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:35>.withTag({entity_id: "minecraft:llama"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:38>.withTag({entity_id: "minecraft:stray"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:39>.withTag({entity_id: "minecraft:husk"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:40>.withTag({entity_id: "minecraft:zombie_villager"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:41>.withTag({entity_id: "minecraft:evocation_illager"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:42>.withTag({entity_id: "minecraft:vex"}));
mods.jei.JEI.removeAndHide(<openblocks:trophy:43>.withTag({entity_id: "minecraft:vindication_illager"}));
//============================================================================================================================================================================================
//CHISEL
mods.jei.JEI.removeAndHide(<chisel:blockinvar:0>);
mods.jei.JEI.removeAndHide(<chisel:blockinvar:1>);
mods.jei.JEI.removeAndHide(<chisel:blockinvar:2>);
mods.jei.JEI.removeAndHide(<chisel:blockinvar:3>);
mods.jei.JEI.removeAndHide(<chisel:blockinvar:4>);
mods.jei.JEI.removeAndHide(<chisel:blockinvar:5>);
mods.jei.JEI.removeAndHide(<chisel:blockinvar:6>);
mods.jei.JEI.removeAndHide(<chisel:blocksilver:0>);
mods.jei.JEI.removeAndHide(<chisel:blocksilver:1>);
mods.jei.JEI.removeAndHide(<chisel:blocksilver:2>);
mods.jei.JEI.removeAndHide(<chisel:blocksilver:3>);
mods.jei.JEI.removeAndHide(<chisel:blocksilver:4>);
mods.jei.JEI.removeAndHide(<chisel:blocksilver:5>);
mods.jei.JEI.removeAndHide(<chisel:blocksilver:6>);
mods.jei.JEI.removeAndHide(<chisel:blockcobalt:0>);
mods.jei.JEI.removeAndHide(<chisel:blockcobalt:1>);
mods.jei.JEI.removeAndHide(<chisel:blockcobalt:2>);
mods.jei.JEI.removeAndHide(<chisel:blockcobalt:3>);
mods.jei.JEI.removeAndHide(<chisel:blockcobalt:4>);
mods.jei.JEI.removeAndHide(<chisel:blockcobalt:5>);
mods.jei.JEI.removeAndHide(<chisel:blockcobalt:6>);
//============================================================================================================================================================================================
//COROUTIL
mods.jei.JEI.removeAndHide(<coroutil:item_repairing_gel>);
mods.jei.JEI.removeAndHide(<coroutil:repairing_block>);
//============================================================================================================================================================================================
//OPEN MODULAR TURRETS
mods.jei.JEI.removeAndHide(<openmodularturrets:addon_meta:3>);
mods.jei.JEI.removeAndHide(<openmodularturrets:addon_meta:5>);
mods.jei.JEI.removeAndHide(<openmodularturrets:usable_meta:0>);
mods.jei.JEI.removeAndHide(<openmodularturrets:usable_meta:1>);
mods.jei.JEI.removeAndHide(<openmodularturrets:addon_meta:2>);
//============================================================================================================================================================================================
//QUARK
mods.jei.JEI.removeAndHide(<quark:spruce_trapdoor>);
mods.jei.JEI.removeAndHide(<quark:birch_trapdoor>);
mods.jei.JEI.removeAndHide(<quark:jungle_trapdoor>);
mods.jei.JEI.removeAndHide(<quark:acacia_trapdoor>);
mods.jei.JEI.removeAndHide(<quark:dark_oak_trapdoor>);
mods.jei.JEI.removeAndHide(<quark:spruce_pressure_plate>);
mods.jei.JEI.removeAndHide(<quark:birch_pressure_plate>);
mods.jei.JEI.removeAndHide(<quark:jungle_pressure_plate>);
mods.jei.JEI.removeAndHide(<quark:acacia_pressure_plate>);
mods.jei.JEI.removeAndHide(<quark:dark_oak_pressure_plate>);
mods.jei.JEI.removeAndHide(<quark:spruce_button>);
mods.jei.JEI.removeAndHide(<quark:birch_button>);
mods.jei.JEI.removeAndHide(<quark:jungle_button>);
mods.jei.JEI.removeAndHide(<quark:acacia_button>);
mods.jei.JEI.removeAndHide(<quark:dark_oak_button>);
mods.jei.JEI.removeAndHide(<quark:frog_leg>);
mods.jei.JEI.removeAndHide(<quark:cooked_frog_leg>);
mods.jei.JEI.removeAndHide(<quark:golden_frog_leg>);
mods.jei.JEI.removeAndHide(<quark:crab_leg>);
mods.jei.JEI.removeAndHide(<quark:cooked_crab_leg>);
mods.jei.JEI.removeAndHide(<quark:monster_box>);
mods.jei.JEI.removeAndHide(<quark:chute>);
//============================================================================================================================================================================================
//PARASITES
mods.jei.JEI.removeAndHide(<overlast:beef_pickaxe>);
mods.jei.JEI.removeAndHide(<overlast:wooden_sword_plus>);
mods.jei.JEI.removeAndHide(<overlast:baseball_pole>);
mods.jei.JEI.removeAndHide(<overlast:ice_spear>);
mods.jei.JEI.removeAndHide(<overlast:drinking_potion:0>);
mods.jei.JEI.removeAndHide(<overlast:drinking_potion:1>);
mods.jei.JEI.removeAndHide(<overlast:drinking_potion:2>);
mods.jei.JEI.removeAndHide(<overlast:drinking_potion:3>);
mods.jei.JEI.removeAndHide(<overlast:injected_potion>);
mods.jei.JEI.removeAndHide(<overlast:boss_chip>);
mods.jei.JEI.removeAndHide(<overlast:blockpurifier>);
mods.jei.JEI.removeAndHide(<overlast:winter_core>);
mods.jei.JEI.removeAndHide(<overlast:summer_core>);
mods.jei.JEI.removeAndHide(<overlast:specimen_farm>);
mods.jei.JEI.removeAndHide(<overlast:specimen_cell>);
mods.jei.JEI.removeAndHide(<overlast:specimen_infect>);
mods.jei.JEI.removeAndHide(<overlast:final_specimen>);
//============================================================================================================================================================================================
//TRAVELERS BACKPACK
mods.jei.JEI.removeAndHide(<travelersbackpack:backpack_tank>);
//============================================================================================================================================================================================
//PARASITUS CORE
mods.jei.JEI.hide(<parasitusfix:door_bunker>);
mods.jei.JEI.hide(<parasitusfix:door_fir>);
mods.jei.JEI.hide(<parasitusfix:door_pine>);
mods.jei.JEI.hide(<parasitusfix:door_palm>);
mods.jei.JEI.hide(<parasitusfix:door_willow>);
mods.jei.JEI.hide(<parasitusfix:door_mangrove>);
mods.jei.JEI.hide(<parasitusfix:door_redwood>);
mods.jei.JEI.hide(<parasitusfix:door_baobab>);
mods.jei.JEI.hide(<parasitusfix:door_cottonwood>);
mods.jei.JEI.hide(<parasitusfix:door_aspen>);
mods.jei.JEI.hide(<parasitusfix:door_maple>);
mods.jei.JEI.hide(<parasitusfix:door_juniper>);
mods.jei.JEI.hide(<parasitusfix:door_cherry_blossom>);
mods.jei.JEI.hide(<parasitusfix:door_jacaranda>);